## Célula 1 - Imports

Esta célula carrega apenas bibliotecas e utilitários. A lógica começa nas células seguintes.

In [1]:
from __future__ import annotations

import hashlib
import json
import logging
import random
import shutil
import zipfile
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import matplotlib
matplotlib.use('Agg', force=True)
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image

try:
    import torch
except Exception:
    torch = None

try:
    from IPython.display import display
except Exception:
    display = print

## Célula 2 - Base do Dataset

Aqui ficam a configuração global, a validação do `.zip` e a análise da distribuição das classes.

In [2]:
PROJECT_ROOT = Path.cwd().resolve()
TRAIN_ZIP_PATH = PROJECT_ROOT / 'train.zip'
VAL_ZIP_PATH = PROJECT_ROOT / 'val.zip'
TEST_ZIP_PATH = PROJECT_ROOT / 'test.zip'
DATASETS_DIR = PROJECT_ROOT / 'datasets'
TRAIN_DIR = DATASETS_DIR / 'train'
VAL_DIR = DATASETS_DIR / 'val'
TEST_DIR = DATASETS_DIR / 'test'
IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
LOGGER = logging.getLogger('notebook')


def ensure_zip_exists(zip_path: Path) -> None:
    if not zip_path.exists():
        raise FileNotFoundError(f'Arquivo zip nao encontrado: {zip_path.resolve()}')


def extract_dataset(zip_path: Path, target_dir: Path) -> Path:
    '''Extract one split from its own zip and return the folder that contains images/labels.'''
    ensure_zip_exists(zip_path)
    if target_dir.exists():
        shutil.rmtree(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as archive:
        archive.extractall(target_dir)

    candidates = [target_dir] + [p for p in target_dir.rglob('*') if p.is_dir()]
    dataset_roots = [p for p in candidates if (p / 'images').is_dir() and (p / 'labels').is_dir()]
    if not dataset_roots:
        raise ValueError(f'{zip_path.name} nao contem uma estrutura valida com images/ e labels/.')
    dataset_root = min(dataset_roots, key=lambda p: len(p.relative_to(target_dir).parts))
    if not (dataset_root / 'classes.txt').exists():
        label_classes = dataset_root / 'labels' / 'classes.txt'
        image_classes = dataset_root / 'images' / 'classes.txt'
        if label_classes.exists():
            shutil.copy2(label_classes, dataset_root / 'classes.txt')
        elif image_classes.exists():
            shutil.copy2(image_classes, dataset_root / 'classes.txt')
        else:
            raise ValueError(f'{zip_path.name} nao contem classes.txt na raiz do split.')
    return dataset_root


def load_class_names(classes_file: Path) -> list[str]:
    if not classes_file.exists():
        raise FileNotFoundError(f'classes.txt nao encontrado: {classes_file.resolve()}')
    names = [line.strip() for line in classes_file.read_text(encoding='utf-8').splitlines() if line.strip()]
    if not names:
        raise ValueError(f'classes.txt vazio: {classes_file.resolve()}')
    return names


def compare_class_lists(*class_lists: list[str]) -> None:
    reference = class_lists[0]
    for index, names in enumerate(class_lists[1:], start=2):
        if names != reference:
            raise ValueError(f'Classes inconsistentes entre splits. Split 1={reference}; split {index}={names}')


def read_label_rows(label_file: Path) -> list[tuple[int, float, float, float, float]]:
    rows: list[tuple[int, float, float, float, float]] = []
    if not label_file.exists() or label_file.name == 'classes.txt':
        return rows
    for line_number, raw_line in enumerate(label_file.read_text(encoding='utf-8').splitlines(), start=1):
        raw_line = raw_line.strip()
        if not raw_line:
            continue
        parts = raw_line.split()
        if len(parts) < 5:
            raise ValueError(f'Label invalido em {label_file.resolve()} linha {line_number}: {raw_line}')
        class_id = int(float(parts[0]))
        coords = tuple(round(float(value), 6) for value in parts[1:5])
        rows.append((class_id, *coords))
    return rows


def read_label_classes(label_file: Path) -> list[int]:
    return [row[0] for row in read_label_rows(label_file)]


def collect_image_hashes(split_root: Path) -> dict[str, list[Path]]:
    hashes: dict[str, list[Path]] = {}
    for image_path in sorted((split_root / 'images').rglob('*')):
        if image_path.suffix.lower() in IMAGE_EXTENSIONS:
            digest = hashlib.sha256(image_path.read_bytes()).hexdigest()
            hashes.setdefault(digest, []).append(image_path)
    return hashes


def collect_coordinate_signatures(split_root: Path) -> dict[tuple[tuple[int, float, float, float, float], ...], list[Path]]:
    signatures: dict[tuple[tuple[int, float, float, float, float], ...], list[Path]] = {}
    for label_path in sorted((split_root / 'labels').rglob('*.txt')):
        if label_path.name == 'classes.txt':
            continue
        rows = tuple(sorted(read_label_rows(label_path)))
        if rows:
            signatures.setdefault(rows, []).append(label_path)
    return signatures


def overlap_rows(kind: str, split_a: str, split_b: str, left: dict[Any, list[Path]], right: dict[Any, list[Path]]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for signature in sorted(set(left).intersection(right), key=str):
        for left_path in left[signature]:
            for right_path in right[signature]:
                rows.append({
                    'tipo': kind,
                    'split_a': split_a,
                    'arquivo_a': str(left_path.resolve()),
                    'split_b': split_b,
                    'arquivo_b': str(right_path.resolve()),
                })
    return rows


def detect_data_leakage(train_root: Path, val_root: Path, test_root: Path) -> None:
    '''Detect leakage. Train/val image overlap warns unless coordinates also overlap; any test overlap fails.'''
    roots = {'train': train_root, 'val': val_root, 'test': test_root}
    image_hashes = {name: collect_image_hashes(root) for name, root in roots.items()}
    coordinate_signatures = {name: collect_coordinate_signatures(root) for name, root in roots.items()}

    train_val_images = overlap_rows('imagem_duplicada', 'train', 'val', image_hashes['train'], image_hashes['val'])
    train_val_coords = overlap_rows('coordenadas_duplicadas', 'train', 'val', coordinate_signatures['train'], coordinate_signatures['val'])
    test_images = overlap_rows('imagem_duplicada', 'train', 'test', image_hashes['train'], image_hashes['test'])
    test_images += overlap_rows('imagem_duplicada', 'val', 'test', image_hashes['val'], image_hashes['test'])
    test_coords = overlap_rows('coordenadas_duplicadas', 'train', 'test', coordinate_signatures['train'], coordinate_signatures['test'])
    test_coords += overlap_rows('coordenadas_duplicadas', 'val', 'test', coordinate_signatures['val'], coordinate_signatures['test'])

    if test_images or test_coords:
        report = pd.DataFrame(test_images + test_coords)
        print('Data leakage envolvendo TEST detectado:')
        display(report)
        raise ValueError('Data leakage envolvendo TEST. TEST nao pode aparecer no treino, validacao, Optuna ou selecao.')

    if train_val_coords:
        report = pd.DataFrame(train_val_coords)
        print('Data leakage entre TRAIN e VAL com as mesmas coordenadas detectado:')
        display(report)
        raise ValueError('Data leakage entre TRAIN e VAL: as mesmas coordenadas/anotacoes aparecem nos dois splits.')

    if train_val_images:
        print('Aviso: possivel data leakage entre TRAIN e VAL por imagem repetida, mas sem conflito de coordenadas iguais.')
        display(pd.DataFrame(train_val_images))
    else:
        print('Nenhum data leakage detectado entre TRAIN, VAL e TEST.')


def build_distribution_table(dataset_root: Path) -> tuple[pd.DataFrame, int, int, list[str]]:
    class_names = load_class_names(dataset_root / 'classes.txt')
    image_files = [p for p in sorted((dataset_root / 'images').rglob('*')) if p.suffix.lower() in IMAGE_EXTENSIONS]
    label_files = [p for p in sorted((dataset_root / 'labels').glob('*.txt')) if p.name != 'classes.txt']
    counts = Counter()
    total_objects = 0
    for label_file in label_files:
        class_ids = read_label_classes(label_file)
        total_objects += len(class_ids)
        counts.update(class_ids)
    rows = []
    for class_id, class_name in enumerate(class_names):
        quantity = int(counts.get(class_id, 0))
        percentage = (quantity / total_objects * 100.0) if total_objects else 0.0
        rows.append({'Classe': class_name, 'Quantidade': quantity, 'Percentual': percentage})
    return pd.DataFrame(rows), len(image_files), total_objects, class_names


def plot_distribution(table: pd.DataFrame, split_name: str) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(18, 6))
    axes[0].bar(table['Classe'], table['Quantidade'], color='#005f73')
    axes[0].set_title(f'{split_name} - Distribuicao por classe')
    axes[0].set_ylabel('Quantidade')
    axes[0].tick_params(axis='x', rotation=45)
    axes[1].pie(table['Quantidade'], labels=table['Classe'], autopct='%1.1f%%', startangle=140)
    axes[1].set_title(f'{split_name} - Participacao percentual')
    plt.tight_layout()
    plt.show()


def report_split_distribution(split_root: Path, split_name: str) -> pd.DataFrame:
    table, image_count, annotation_count, _ = build_distribution_table(split_root)
    print(f'[{split_name}] origem: {(PROJECT_ROOT / (split_name.lower() + ".zip")).resolve()}')
    print(f'[{split_name}] imagens: {image_count}')
    print(f'[{split_name}] anotacoes: {annotation_count}')
    display(table)
    plot_distribution(table, split_name)
    return table


TRAIN_ROOT = extract_dataset(TRAIN_ZIP_PATH, TRAIN_DIR)
VAL_ROOT = extract_dataset(VAL_ZIP_PATH, VAL_DIR)
TEST_ROOT = extract_dataset(TEST_ZIP_PATH, TEST_DIR)

print(f'Train extraido apenas de: {TRAIN_ZIP_PATH.resolve()} -> {TRAIN_ROOT.resolve()}')
print(f'Val extraido apenas de: {VAL_ZIP_PATH.resolve()} -> {VAL_ROOT.resolve()}')
print(f'Test extraido apenas de: {TEST_ZIP_PATH.resolve()} -> {TEST_ROOT.resolve()}')

TRAIN_CLASSES = load_class_names(TRAIN_ROOT / 'classes.txt')
VAL_CLASSES = load_class_names(VAL_ROOT / 'classes.txt')
TEST_CLASSES = load_class_names(TEST_ROOT / 'classes.txt')
compare_class_lists(TRAIN_CLASSES, VAL_CLASSES, TEST_CLASSES)
detect_data_leakage(TRAIN_ROOT, VAL_ROOT, TEST_ROOT)

DISTRIBUTION_TRAIN = report_split_distribution(TRAIN_ROOT, 'TRAIN')
DISTRIBUTION_VAL = report_split_distribution(VAL_ROOT, 'VAL')
DISTRIBUTION_TEST = report_split_distribution(TEST_ROOT, 'TEST')

majority_row = DISTRIBUTION_TRAIN.loc[DISTRIBUTION_TRAIN['Quantidade'].idxmax()]
minority_row = DISTRIBUTION_TRAIN.loc[DISTRIBUTION_TRAIN['Quantidade'].idxmin()]
minority_value = float(minority_row['Quantidade'])
majority_value = float(majority_row['Quantidade'])
imbalance_ratio = (majority_value / minority_value) if minority_value else float('inf')

print(f'Total de objetos no TRAIN: {int(DISTRIBUTION_TRAIN["Quantidade"].sum())}')
print(f'Classe majoritaria no TRAIN: {majority_row["Classe"]}')
print(f'Classe minoritaria no TRAIN: {minority_row["Classe"]}')
print(f'Razao de desbalanceamento no TRAIN: {imbalance_ratio:.2f}')

Train extraido apenas de: C:\Users\Enzo\Desktop\rp\train.zip -> C:\Users\Enzo\Desktop\rp\datasets\train
Val extraido apenas de: C:\Users\Enzo\Desktop\rp\val.zip -> C:\Users\Enzo\Desktop\rp\datasets\val
Test extraido apenas de: C:\Users\Enzo\Desktop\rp\test.zip -> C:\Users\Enzo\Desktop\rp\datasets\test
Aviso: possivel data leakage entre TRAIN e VAL por imagem repetida, mas sem conflito de coordenadas iguais.

,tipo,split_a,arquivo_a,split_b,arquivo_b
0,imagem_duplicada,train,C:\Users\Enzo\Desktop\rp\datasets\train\images...,val,C:\Users\Enzo\Desktop\rp\datasets\val\images\8...
1,imagem_duplicada,train,C:\Users\Enzo\Desktop\rp\datasets\train\images...,val,C:\Users\Enzo\Desktop\rp\datasets\val\images\8...
2,imagem_duplicada,train,C:\Users\Enzo\Desktop\rp\datasets\train\images...,val,C:\Users\Enzo\Desktop\rp\datasets\val\images\8...
3,imagem_duplicada,train,C:\Users\Enzo\Desktop\rp\datasets\train\images...,val,C:\Users\Enzo\Desktop\rp\datasets\val\images\e...
4,imagem_duplicada,train,C:\Users\Enzo\Desktop\rp\datasets\train\images...,val,C:\Users\Enzo\Desktop\rp\datasets\val\images\f...
5,imagem_duplicada,train,C:\Users\Enzo\Desktop\rp\datasets\train\images...,val,C:\Users\Enzo\Desktop\rp\datasets\val\images\b...
6,imagem_duplicada,train,C:\Users\Enzo\Desktop\rp\datasets\train\images...,val,C:\Users\Enzo\Desktop\rp\datasets\val\images\b...

[TRAIN] origem: C:\Users\Enzo\Desktop\rp\train.zip
[TRAIN] imagens: 183
[TRAIN] anotacoes: 471

                  Classe  Quantidade  Percentual
0                     C+          58   12.314225
1                     R+          55   11.677282
2                     R-          48   10.191083
3            R/CFaltante          57   12.101911
4              Soldagem+          89   18.895966
5  SoldagemCurtoCircuito          48   10.191083
6       SoldagemFaltante          53   11.252654
7                     U+          42    8.917197
8              UFaltante          21    4.458599

[VAL] origem: C:\Users\Enzo\Desktop\rp\val.zip
[VAL] imagens: 19
[VAL] anotacoes: 103

C:\Users\Enzo\AppData\Local\Temp\ipykernel_11688\4215971124.py:177: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

                  Classe  Quantidade  Percentual
0                     C+          16   15.533981
1                     R+          16   15.533981
2                     R-           2    1.941748
3            R/CFaltante          16   15.533981
4              Soldagem+          16   15.533981
5  SoldagemCurtoCircuito           2    1.941748
6       SoldagemFaltante          13   12.621359
7                     U+          16   15.533981
8              UFaltante           6    5.825243

[TEST] origem: C:\Users\Enzo\Desktop\rp\test.zip
[TEST] imagens: 8
[TEST] anotacoes: 69

C:\Users\Enzo\AppData\Local\Temp\ipykernel_11688\4215971124.py:177: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

                  Classe  Quantidade  Percentual
0                     C+          12   17.391304
1                     R+          12   17.391304
2                     R-           1    1.449275
3            R/CFaltante          13   18.840580
4              Soldagem+          11   15.942029
5  SoldagemCurtoCircuito           1    1.449275
6       SoldagemFaltante           8   11.594203
7                     U+           8   11.594203
8              UFaltante           3    4.347826

Total de objetos no TRAIN: 471
Classe majoritaria no TRAIN: Soldagem+
Classe minoritaria no TRAIN: UFaltante
Razao de desbalanceamento no TRAIN: 4.24

C:\Users\Enzo\AppData\Local\Temp\ipykernel_11688\4215971124.py:177: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Célula 3 - Carregamento dos Conjuntos
Recebe train.zip, val.zip e test.zip já separados. Não é realizado split estratificado.

In [3]:
import yaml

CLASS_NAMES = TRAIN_CLASSES
DATASET_YAML = PROJECT_ROOT / 'data.yaml'

dataset_yaml = {
    'path': str(DATASETS_DIR.resolve()),
    'train': str((TRAIN_ROOT / 'images').resolve()),
    'val': str((VAL_ROOT / 'images').resolve()),
    'test': str((TEST_ROOT / 'images').resolve()),
    'nc': len(CLASS_NAMES),
    'names': CLASS_NAMES,
}


def validate_dataset_yaml(yaml_payload: dict[str, Any], expected_class_names: list[str]) -> None:
    expected_paths = {
        'train': str((TRAIN_ROOT / 'images').resolve()),
        'val': str((VAL_ROOT / 'images').resolve()),
        'test': str((TEST_ROOT / 'images').resolve()),
    }
    for key, expected_value in expected_paths.items():
        if yaml_payload.get(key) != expected_value:
            raise ValueError(f'Dataset YAML inconsistente em {key}: esperado {expected_value}, obtido {yaml_payload.get(key)}')
    if yaml_payload.get('path') != str(DATASETS_DIR.resolve()):
        raise ValueError('Dataset YAML com path incorreto.')
    if int(yaml_payload.get('nc', -1)) != len(expected_class_names):
        raise ValueError('Dataset YAML com nc incorreto.')
    if list(yaml_payload.get('names', [])) != expected_class_names:
        raise ValueError('Dataset YAML com names incorreto.')


validate_dataset_yaml(dataset_yaml, CLASS_NAMES)
with DATASET_YAML.open('w', encoding='utf-8') as handle:
    yaml.safe_dump(dataset_yaml, handle, allow_unicode=True, sort_keys=False)

print('data.yaml criado e validado:')
print(DATASET_YAML.resolve())
print(dataset_yaml)

data.yaml criado e validado:
C:\Users\Enzo\Desktop\rp\data.yaml
{'path': 'C:\\Users\\Enzo\\Desktop\\rp\\datasets', 'train': 'C:\\Users\\Enzo\\Desktop\\rp\\datasets\\train\\images', 'val': 'C:\\Users\\Enzo\\Desktop\\rp\\datasets\\val\\images', 'test': 'C:\\Users\\Enzo\\Desktop\\rp\\datasets\\test\\images', 'nc': 9, 'names': ['C+', 'R+', 'R-', 'R/CFaltante', 'Soldagem+', 'SoldagemCurtoCircuito', 'SoldagemFaltante', 'U+', 'UFaltante']}

## Célula 4 - Treino e Comparação

Aqui estão os controles de modelo, métrica, Optuna e treinamento final.

In [ ]:
# Configurações principais do experimento.
import json
import os
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping

import numpy as np
import pandas as pd
import torchvision

MODEL_NAME = 'YOLO'
USE_OPTUNA = True
N_TRIALS = 10
OPTIMIZATION_METRIC = 'mAP50'

COMPARE_MODELS = ['YOLO', 'T-DETR', 'Faster R-CNN']
ARTIFACTS_DIR = PROJECT_ROOT / 'training_artifacts'
TRAINING_SUMMARY_CSV = PROJECT_ROOT / 'training_summary.csv'
BEST_HYPERPARAMETERS_JSON = PROJECT_ROOT / 'best_hyperparameters.json'
BEST_MODEL_PATH = PROJECT_ROOT / 'best_model.pt'
CONFUSION_MATRIX_DIR = PROJECT_ROOT / 'confusion_matrices'

DEFAULT_HYPERPARAMETERS = {
    'epochs': 60,
    'batch_size': 8,
    'learning_rate': 0.001,
    'weight_decay': 0.0005,
    'optimizer': 'AdamW',
    'img_size': 640,
    'momentum': 0.937,
    'scheduler': 'cosine',
    'patience': 20,
}


@dataclass
class RunArtifacts:
    '''Store the relevant paths and scores for a training run.'''

    model_name: str
    best_metric: float
    best_weights: Path
    best_params: dict[str, Any]


def set_global_seed(seed: int) -> None:
    '''Seed every available backend.'''
    random.seed(seed)
    np.random.seed(seed)
    if torch is not None:
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)


def resolve_device() -> int:
    '''Require CUDA and use only GPU for training, validation and inference.'''
    if torch is None:
        raise RuntimeError('PyTorch nao esta disponivel. Instale torch com suporte a CUDA antes de treinar.')
    if not torch.cuda.is_available():
        raise RuntimeError('GPU/CUDA obrigatoria: este notebook foi configurado para nao executar em CPU.')
    return 0


def available_workers() -> int:
    '''Keep data-loader workers conservative for notebook environments.'''
    cpu_count = max(1, os.cpu_count() or 1)
    return max(1, min(2, cpu_count // 2))


def metric_lookup(metrics: Any, metric_name: str) -> float:
    '''Normalize metric access across compatible backends.'''
    normalized = metric_name.lower()
    if isinstance(metrics, Mapping) and metric_name in metrics:
        return float(metrics[metric_name])
    if hasattr(metrics, 'results_dict'):
        results = metrics.results_dict
        candidates = {
            'map50': ['metrics/mAP50(B)', 'metrics/mAP50'],
            'map50-95': ['metrics/mAP50-95(B)', 'metrics/mAP50-95'],
            'precision': ['metrics/precision(B)', 'metrics/precision'],
            'recall': ['metrics/recall(B)', 'metrics/recall'],
            'f1': ['metrics/F1(B)', 'metrics/F1'],
        }
        for key in candidates.get(normalized, []):
            if key in results:
                return float(results[key])
    if hasattr(metrics, 'metrics') and isinstance(metrics.metrics, Mapping) and metric_name in metrics.metrics:
        return float(metrics.metrics[metric_name])
    raise KeyError(f'Metrica nao encontrada: {metric_name}')


def sample_optuna_params(trial: Any) -> dict[str, Any]:
    '''Sample the explicit Optuna search space.'''
    return {
        'epochs': trial.suggest_int('epochs', 20, 120, step=10),
        'batch_size': trial.suggest_categorical('batch_size', [4, 8]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-5, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 0.0, 5e-3),
        'optimizer': trial.suggest_categorical('optimizer', ['SGD', 'Adam', 'AdamW']),
        'img_size': trial.suggest_categorical('img_size', [512, 640]),
        'momentum': trial.suggest_float('momentum', 0.8, 0.99),
        'scheduler': trial.suggest_categorical('scheduler', ['cosine', 'onecycle', 'step']),
        'patience': trial.suggest_int('patience', 10, 30, step=5),
    }


def _ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def load_labels_for_image(label_file: Path) -> list[list[float]]:
    '''Load YOLO labels as [class, x, y, w, h].'''
    labels: list[list[float]] = []
    if not label_file.exists():
        return labels
    with label_file.open('r', encoding='utf-8') as handle:
        for raw_line in handle:
            raw_line = raw_line.strip()
            if not raw_line:
                continue
            parts = raw_line.split()
            if len(parts) < 5:
                continue
            try:
                labels.append([float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3]), float(parts[4])])
            except ValueError:
                continue
    return labels


def yolo_to_xyxy(label_row: list[float], width: int, height: int) -> list[float]:
    class_id, x_center, y_center, box_width, box_height = label_row
    x1 = (x_center - box_width / 2.0) * width
    y1 = (y_center - box_height / 2.0) * height
    x2 = (x_center + box_width / 2.0) * width
    y2 = (y_center + box_height / 2.0) * height
    return [x1, y1, x2, y2, class_id]


def compute_iou(box_a: list[float], box_b: list[float]) -> float:
    '''Compute IoU between two xyxy boxes.'''
    ax1, ay1, ax2, ay2 = box_a
    bx1, by1, bx2, by2 = box_b
    inter_x1 = max(ax1, bx1)
    inter_y1 = max(ay1, by1)
    inter_x2 = min(ax2, bx2)
    inter_y2 = min(ay2, by2)
    inter_w = max(0.0, inter_x2 - inter_x1)
    inter_h = max(0.0, inter_y2 - inter_y1)
    inter_area = inter_w * inter_h
    area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    union = area_a + area_b - inter_area
    return inter_area / union if union > 0 else 0.0


def collect_ground_truth(split_root: Path) -> dict[str, dict[str, Any]]:
    '''Collect ground-truth boxes and labels for a split.'''
    items: dict[str, dict[str, Any]] = {}
    images_dir = split_root / 'images'
    labels_dir = split_root / 'labels'
    for image_path in sorted(images_dir.rglob('*')):
        if image_path.suffix.lower() not in IMAGE_EXTENSIONS:
            continue
        with Image.open(image_path) as img:
            width, height = img.size
        label_file = labels_dir / f'{image_path.stem}.txt'
        labels = [yolo_to_xyxy(row, width, height) for row in load_labels_for_image(label_file)]
        items[image_path.stem] = {
            'image_path': image_path,
            'width': width,
            'height': height,
            'labels': labels,
        }
    return items


def _empty_prediction_payload() -> dict[str, list[Any]]:
    return {'boxes': [], 'scores': [], 'labels': []}


def _result_boxes_to_lists(result: Any) -> dict[str, list[Any]]:
    boxes = getattr(result, 'boxes', None)
    if boxes is None:
        return _empty_prediction_payload()
    xyxy = boxes.xyxy.cpu().numpy().tolist() if hasattr(boxes, 'xyxy') else []
    scores = boxes.conf.cpu().numpy().tolist() if hasattr(boxes, 'conf') else []
    labels = boxes.cls.cpu().numpy().tolist() if hasattr(boxes, 'cls') else []
    return {'boxes': xyxy, 'scores': scores, 'labels': labels}


def match_predictions_to_gt(pred_boxes: list[list[float]], pred_labels: list[int], pred_scores: list[float], gt_boxes: list[list[float]], gt_labels: list[int], num_classes: int, iou_threshold: float) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    '''Greedy matching of predictions to ground truth for one IoU threshold using class-aware matching.'''
    tp = np.zeros(num_classes, dtype=float)
    fp = np.zeros(num_classes, dtype=float)
    fn = np.zeros(num_classes, dtype=float)
    gt_used = [False] * len(gt_boxes)
    order = np.argsort(-np.asarray(pred_scores)) if pred_scores else np.array([], dtype=int)
    for pred_index in order:
        pred_box = pred_boxes[pred_index]
        pred_label = int(pred_labels[pred_index])
        best_iou = 0.0
        best_gt_index = -1
        for gt_index, (gt_box, gt_label) in enumerate(zip(gt_boxes, gt_labels)):
            if gt_used[gt_index] or int(gt_label) != pred_label:
                continue
            current_iou = compute_iou(pred_box, gt_box)
            if current_iou > best_iou:
                best_iou = current_iou
                best_gt_index = gt_index
        if best_gt_index >= 0 and best_iou >= iou_threshold:
            tp[pred_label] += 1
            gt_used[best_gt_index] = True
        else:
            fp[pred_label] += 1
    for gt_index, gt_label in enumerate(gt_labels):
        if not gt_used[gt_index]:
            fn[int(gt_label)] += 1
    return tp, fp, fn


def match_for_confusion(pred_boxes: list[list[float]], pred_labels: list[int], pred_scores: list[float], gt_boxes: list[list[float]], gt_labels: list[int], num_classes: int, iou_threshold: float) -> np.ndarray:
    '''Build a true-vs-predicted confusion matrix using IoU matching.'''
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=float)
    gt_used = [False] * len(gt_boxes)
    order = np.argsort(-np.asarray(pred_scores)) if pred_scores else np.array([], dtype=int)
    for pred_index in order:
        pred_box = pred_boxes[pred_index]
        pred_label = int(pred_labels[pred_index])
        best_iou = 0.0
        best_gt_index = -1
        for gt_index, gt_box in enumerate(gt_boxes):
            if gt_used[gt_index]:
                continue
            current_iou = compute_iou(pred_box, gt_box)
            if current_iou > best_iou:
                best_iou = current_iou
                best_gt_index = gt_index
        if best_gt_index >= 0 and best_iou >= iou_threshold:
            gt_label = int(gt_labels[best_gt_index])
            confusion_matrix[gt_label, pred_label] += 1
            gt_used[best_gt_index] = True
    return confusion_matrix


def evaluate_detections(ground_truth: dict[str, dict[str, Any]], predictions: dict[str, dict[str, list[Any]]], class_names: list[str]) -> tuple[pd.DataFrame, np.ndarray, dict[str, float]]:
    '''Evaluate predictions against ground truth on multiple IoU thresholds.'''
    num_classes = len(class_names)
    iou_thresholds = np.arange(0.5, 0.96, 0.05)
    ap50_per_class = np.zeros(num_classes, dtype=float)
    ap50_95_per_class = np.zeros(num_classes, dtype=float)
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=float)
    base_tp = np.zeros(num_classes, dtype=float)
    base_fp = np.zeros(num_classes, dtype=float)
    base_fn = np.zeros(num_classes, dtype=float)

    for threshold_index, threshold in enumerate(iou_thresholds):
        threshold_tp = np.zeros(num_classes, dtype=float)
        threshold_fp = np.zeros(num_classes, dtype=float)
        threshold_fn = np.zeros(num_classes, dtype=float)
        for stem, gt_data in ground_truth.items():
            pred_data = predictions.get(stem, _empty_prediction_payload())
            pred_boxes = [list(map(float, box)) for box in pred_data['boxes']]
            pred_labels = [int(label) for label in pred_data['labels']]
            pred_scores = [float(score) for score in pred_data['scores']]
            gt_boxes = [box[:4] for box in gt_data['labels']]
            gt_labels = [int(box[4]) for box in gt_data['labels']]
            tp, fp, fn = match_predictions_to_gt(pred_boxes, pred_labels, pred_scores, gt_boxes, gt_labels, num_classes, float(threshold))
            threshold_tp += tp
            threshold_fp += fp
            threshold_fn += fn
            if threshold_index == 0:
                base_tp += tp
                base_fp += fp
                base_fn += fn
                confusion_matrix += match_for_confusion(pred_boxes, pred_labels, pred_scores, gt_boxes, gt_labels, num_classes, threshold)
        for class_id in range(num_classes):
            precision = threshold_tp[class_id] / (threshold_tp[class_id] + threshold_fp[class_id]) if (threshold_tp[class_id] + threshold_fp[class_id]) else 0.0
            recall = threshold_tp[class_id] / (threshold_tp[class_id] + threshold_fn[class_id]) if (threshold_tp[class_id] + threshold_fn[class_id]) else 0.0
            ap_value = precision * recall
            if threshold_index == 0:
                ap50_per_class[class_id] = ap_value
            ap50_95_per_class[class_id] += ap_value

    ap50_95_per_class /= float(len(iou_thresholds))
    precision = float(base_tp.sum() / (base_tp.sum() + base_fp.sum())) if (base_tp.sum() + base_fp.sum()) else 0.0
    recall = float(base_tp.sum() / (base_tp.sum() + base_fn.sum())) if (base_tp.sum() + base_fn.sum()) else 0.0
    f1 = float((2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0)
    metrics = {
        'Accuracy': float(np.trace(confusion_matrix) / confusion_matrix.sum()) if confusion_matrix.sum() else 0.0,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1,
        'mAP50': float(np.mean(ap50_per_class)) if ap50_per_class.size else 0.0,
        'mAP50-95': float(np.mean(ap50_95_per_class)) if ap50_95_per_class.size else 0.0,
    }
    rows = []
    for class_id, class_name in enumerate(class_names):
        rows.append({'Classe': class_name, 'AP50': float(ap50_per_class[class_id]), 'AP50-95': float(ap50_95_per_class[class_id])})
    return pd.DataFrame(rows), confusion_matrix, metrics

def save_confusion_outputs(cm: np.ndarray, class_names: list[str], model_name: str) -> None:
    '''Save confusion matrix as CSV and PNG.'''
    _ensure_dir(CONFUSION_MATRIX_DIR)
    slug = model_name.replace(' ', '_').lower()
    csv_path = CONFUSION_MATRIX_DIR / f'{slug}_confusion_matrix.csv'
    png_path = CONFUSION_MATRIX_DIR / f'{slug}_confusion_matrix.png'
    frame = pd.DataFrame(cm, index=class_names, columns=class_names)
    frame.to_csv(csv_path, index=True, encoding='utf-8')
    plt.figure(figsize=(12, 10))
    plt.imshow(cm, cmap='Blues')
    plt.title(f'Matriz de confusao - {model_name}')
    plt.colorbar()
    ticks = np.arange(len(class_names))
    plt.xticks(ticks, class_names, rotation=45, ha='right')
    plt.yticks(ticks, class_names)
    plt.xlabel('Predito')
    plt.ylabel('Real')
    for row_index in range(cm.shape[0]):
        for col_index in range(cm.shape[1]):
            plt.text(col_index, row_index, f'{cm[row_index, col_index]:.0f}', ha='center', va='center', color='black')
    plt.tight_layout()
    plt.savefig(png_path, dpi=200, bbox_inches='tight')
    plt.show()


class YoloBackend:
    '''Backend wrapper for Ultralytics YOLO.'''

    def __init__(self, model_name: str, class_names: list[str], dataset_yaml: Path, project_dir: Path) -> None:
        from ultralytics import YOLO

        self.model_name = model_name
        self.YOLO = YOLO
        self.class_names = class_names
        self.dataset_yaml = dataset_yaml
        self.project_dir = project_dir

    def train(self, params: Mapping[str, Any], run_name: str) -> Path:
        model = self.YOLO(self._resolve_weights())
        result = model.train(
            data=str(self.dataset_yaml),
            epochs=int(params['epochs']),
            batch=int(params['batch_size']),
            imgsz=int(params['img_size']),
            lr0=float(params['learning_rate']),
            weight_decay=float(params['weight_decay']),
            optimizer=str(params['optimizer']),
            momentum=float(params['momentum']),
            patience=int(params['patience']),
            device=resolve_device(),
            workers=available_workers(),
            project=str(self.project_dir),
            name=run_name,
            exist_ok=True,
            cache=False,
            amp=True,
            verbose=False,
            val=True,
            save=True,
        )
        return Path(result.save_dir) / 'weights' / 'best.pt'

    def evaluate(self, weights: Path, split: str = 'val', imgsz: int = 640) -> Any:
        model = self.YOLO(str(weights))
        return model.val(data=str(self.dataset_yaml), split=split, imgsz=imgsz, device=resolve_device(), verbose=False)

    def predict(self, weights: Path, source: Path, save_dir: Path) -> dict[str, dict[str, list[Any]]]:
        model = self.YOLO(str(weights))
        results = model.predict(source=str(source), save=False, project=str(save_dir), exist_ok=True, device=resolve_device(), verbose=False)
        predictions: dict[str, dict[str, list[Any]]] = {}
        for result in results:
            stem = Path(result.path).stem
            predictions[stem] = _result_boxes_to_lists(result)
        return predictions

    def _resolve_weights(self) -> str:
        return 'yolov8s.pt'


class TDETRBackend:
    '''Backend wrapper for Ultralytics RT-DETR style models.'''

    def __init__(self, model_name: str, class_names: list[str], dataset_yaml: Path, project_dir: Path) -> None:
        try:
            from ultralytics import RTDETR  # type: ignore
            self.Model = RTDETR
        except Exception:
            from ultralytics import YOLO  # type: ignore
            self.Model = YOLO
        self.model_name = model_name
        self.class_names = class_names
        self.dataset_yaml = dataset_yaml
        self.project_dir = project_dir

    def train(self, params: Mapping[str, Any], run_name: str) -> Path:
        model = self.Model(self._resolve_weights())
        result = model.train(
            data=str(self.dataset_yaml),
            epochs=int(params['epochs']),
            batch=int(params['batch_size']),
            imgsz=int(params['img_size']),
            lr0=float(params['learning_rate']),
            momentum=float(params['momentum']),
            patience=int(params['patience']),
            device=resolve_device(),
            workers=available_workers(),
            project=str(self.project_dir),
            name=run_name,
            exist_ok=True,
            cache=False,
            amp=True,
            verbose=False,
            val=True,
            save=True,
        )
        return Path(result.save_dir) / 'weights' / 'best.pt'

    def evaluate(self, weights: Path, split: str = 'val', imgsz: int = 640) -> Any:
        model = self.Model(str(weights))
        return model.val(data=str(self.dataset_yaml), split=split, imgsz=imgsz, device=resolve_device(), verbose=False)

    def predict(self, weights: Path, source: Path, save_dir: Path) -> dict[str, dict[str, list[Any]]]:
        model = self.Model(str(weights))
        results = model.predict(source=str(source), save=False, project=str(save_dir), exist_ok=True, device=resolve_device(), verbose=False)
        predictions: dict[str, dict[str, list[Any]]] = {}
        for result in results:
            stem = Path(result.path).stem
            predictions[stem] = _result_boxes_to_lists(result)
        return predictions

    def _resolve_weights(self) -> str:
        return 'rtdetr-l.pt'


class FasterRCNNDataset(torch.utils.data.Dataset):
    '''Torchvision dataset for YOLO labels.'''

    def __init__(self, split_root: Path, class_names: list[str]) -> None:
        self.split_root = split_root
        self.class_names = class_names
        self.image_paths = [path for path in sorted((split_root / 'images').rglob('*')) if path.suffix.lower() in IMAGE_EXTENSIONS]

    def __len__(self) -> int:
        return len(self.image_paths)

    def __getitem__(self, index: int) -> tuple[Any, dict[str, torch.Tensor]]:
        image_path = self.image_paths[index]
        label_path = self.split_root / 'labels' / f'{image_path.stem}.txt'
        image = Image.open(image_path).convert('RGB')
        width, height = image.size
        raw_labels = load_labels_for_image(label_path)
        boxes = []
        labels = []
        for row in raw_labels:
            xyxy = yolo_to_xyxy(row, width, height)
            boxes.append(xyxy[:4])
            labels.append(int(xyxy[4]) + 1)
        image_tensor = torchvision.transforms.functional.to_tensor(image)
        target = {
            'boxes': torch.tensor(boxes, dtype=torch.float32) if boxes else torch.zeros((0, 4), dtype=torch.float32),
            'labels': torch.tensor(labels, dtype=torch.int64) if labels else torch.zeros((0,), dtype=torch.int64),
            'image_id': torch.tensor([index]),
            'area': torch.tensor([(box[2] - box[0]) * (box[3] - box[1]) for box in boxes], dtype=torch.float32) if boxes else torch.zeros((0,), dtype=torch.float32),
            'iscrowd': torch.zeros((len(boxes),), dtype=torch.int64),
        }
        return image_tensor, target


def faster_rcnn_model(num_classes: int) -> torch.nn.Module:
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights='DEFAULT')
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = torchvision.models.detection.faster_rcnn.FastRCNNPredictor(in_features, num_classes)
    return model


class FasterRCNNBackend:
    '''Real Faster R-CNN backend with training, validation, inference and evaluation.'''

    def __init__(self, model_name: str, class_names: list[str], dataset_yaml: Path, project_dir: Path) -> None:
        self.model_name = model_name
        self.class_names = class_names
        self.dataset_yaml = dataset_yaml
        self.project_dir = project_dir
        self.device = torch.device(f'cuda:{resolve_device()}')

    def train(self, params: Mapping[str, Any], run_name: str) -> Path:
        train_dataset = FasterRCNNDataset(TRAIN_ROOT, self.class_names)
        train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=int(params['batch_size']), shuffle=True, num_workers=available_workers(), collate_fn=lambda batch: tuple(zip(*batch)))
        model = faster_rcnn_model(len(self.class_names) + 1).to(self.device)
        optimizer = torch.optim.AdamW(model.parameters(), lr=float(params['learning_rate']), weight_decay=float(params['weight_decay']))
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)
        best_metric = -1.0
        run_dir = _ensure_dir(self.project_dir / run_name)
        best_path = run_dir / 'weights' / 'best.pt'
        _ensure_dir(best_path.parent)
        patience = int(params['patience'])
        epochs_without_improvement = 0

        for _epoch in range(int(params['epochs'])):
            model.train()
            for images, targets in train_loader:
                images = [image.to(self.device) for image in images]
                targets = [{key: value.to(self.device) for key, value in target.items()} for target in targets]
                loss_dict = model(images, targets)
                losses = sum(loss for loss in loss_dict.values())
                optimizer.zero_grad()
                losses.backward()
                optimizer.step()
            lr_scheduler.step()
            val_metrics = self.evaluate_model(model, VAL_ROOT)
            current_metric = val_metrics['mAP50']
            if current_metric > best_metric:
                best_metric = current_metric
                torch.save(model.state_dict(), best_path)
                epochs_without_improvement = 0
            else:
                epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                break
        return best_path

    def load_model(self, weights: Path) -> torch.nn.Module:
        model = faster_rcnn_model(len(self.class_names) + 1).to(self.device)
        state_dict = torch.load(weights, map_location=self.device)
        model.load_state_dict(state_dict)
        model.eval()
        return model

    def predict(self, weights: Path, source: Path, save_dir: Path) -> dict[str, dict[str, list[Any]]]:
        model = self.load_model(weights)
        _ensure_dir(save_dir)
        predictions: dict[str, dict[str, list[Any]]] = {}
        for image_path in sorted(source.rglob('*')):
            if image_path.suffix.lower() not in IMAGE_EXTENSIONS:
                continue
            image = Image.open(image_path).convert('RGB')
            tensor = torchvision.transforms.functional.to_tensor(image).to(self.device)
            with torch.no_grad():
                output = model([tensor])[0]
            predictions[image_path.stem] = {
                'boxes': output['boxes'].detach().cpu().numpy().tolist(),
                'scores': output['scores'].detach().cpu().numpy().tolist(),
                'labels': [int(label) - 1 for label in output['labels'].detach().cpu().numpy().tolist()],
            }
        return predictions

    def evaluate_model(self, model: torch.nn.Module, split_root: Path) -> dict[str, float]:
        model.eval()
        ground_truth = collect_ground_truth(split_root)
        predictions: dict[str, dict[str, list[Any]]] = {}
        for image_path in sorted((split_root / 'images').rglob('*')):
            if image_path.suffix.lower() not in IMAGE_EXTENSIONS:
                continue
            image = Image.open(image_path).convert('RGB')
            tensor = torchvision.transforms.functional.to_tensor(image).to(self.device)
            with torch.no_grad():
                output = model([tensor])[0]
            predictions[image_path.stem] = {
                'boxes': output['boxes'].detach().cpu().numpy().tolist(),
                'scores': output['scores'].detach().cpu().numpy().tolist(),
                'labels': [int(label) - 1 for label in output['labels'].detach().cpu().numpy().tolist()],
            }
        _, cm, metrics = evaluate_detections(ground_truth, predictions, self.class_names)
        metrics['confusion_matrix'] = cm
        return metrics

    def evaluate(self, weights: Path, split: str = 'val', imgsz: int = 640) -> Any:
        if split != 'val':
            raise ValueError('Faster R-CNN usa evaluate() apenas em VAL; TEST fica restrito a evaluate_model_on_test().')
        model = self.load_model(weights)
        split_root = VAL_ROOT
        ground_truth = collect_ground_truth(split_root)
        predictions = self.predict(weights, split_root / 'images', self.project_dir / 'predictions' / split)
        _, cm, metrics = evaluate_detections(ground_truth, predictions, self.class_names)
        metrics['confusion_matrix'] = cm
        return metrics


def build_backend(model_name: str, class_names: list[str], dataset_yaml: Path, project_dir: Path) -> Any:
    '''Create the backend for the selected model.'''
    if model_name == 'YOLO':
        return YoloBackend(model_name=model_name, class_names=class_names, dataset_yaml=dataset_yaml, project_dir=project_dir)
    if model_name == 'T-DETR':
        return TDETRBackend(model_name=model_name, class_names=class_names, dataset_yaml=dataset_yaml, project_dir=project_dir)
    if model_name == 'Faster R-CNN':
        return FasterRCNNBackend(model_name=model_name, class_names=class_names, dataset_yaml=dataset_yaml, project_dir=project_dir)
    raise NotImplementedError(f'Nenhum backend foi registrado para {model_name}. Registre o adaptador em build_backend().')


def run_hyperparameter_search(model_name: str, backend_factory: Callable[[Path], Any], metric_name: str) -> tuple[dict[str, Any], float, Path]:
    '''Search hyperparameters using TRAIN for fitting and VAL for model selection.'''
    try:
        import optuna
    except Exception as exc:
        raise ImportError('A biblioteca optuna nao esta disponivel.') from exc

    study = optuna.create_study(direction='maximize')

    def objective(trial: Any) -> float:
        params = sample_optuna_params(trial)
        backend = backend_factory(DATASET_YAML)
        weights = backend.train(params=params, run_name=f'{model_name}_trial_{trial.number}')
        val_metrics = backend.evaluate(weights=weights, split='val', imgsz=int(params['img_size']))
        trial.set_user_attr('weights', str(weights))
        return metric_lookup(val_metrics, metric_name)

    study.optimize(objective, n_trials=N_TRIALS)
    best_params = DEFAULT_HYPERPARAMETERS.copy()
    best_params.update(study.best_trial.params)
    best_weights = Path(study.best_trial.user_attrs['weights'])
    return best_params, float(study.best_value), best_weights


def train_final_model(model_name: str, backend_factory: Callable[[Path], Any], params: Mapping[str, Any]) -> RunArtifacts:
    '''Train the selected model with TRAIN and select using VAL.'''
    backend = backend_factory(DATASET_YAML)
    weights = backend.train(params=params, run_name=f'{model_name}_final')
    val_metrics = backend.evaluate(weights=weights, split='val', imgsz=int(params['img_size']))
    best_metric = metric_lookup(val_metrics, OPTIMIZATION_METRIC)
    return RunArtifacts(model_name=model_name, best_metric=best_metric, best_weights=weights, best_params=dict(params))


def save_json(payload: Mapping[str, Any], path: Path) -> None:
    '''Persist a JSON payload.'''
    with path.open('w', encoding='utf-8') as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, default=str)


def save_summary(rows: list[dict[str, Any]], path: Path) -> None:
    '''Persist the training summary table.'''
    pd.DataFrame(rows).to_csv(path, index=False)


def run_model_workflow(model_name: str) -> RunArtifacts:
    '''Run hyperparameter selection and final training for a single model.'''
    backend_factory = lambda dataset_yaml: build_backend(model_name, CLASS_NAMES, dataset_yaml, ARTIFACTS_DIR / model_name)
    best_params, best_score, best_weights = run_hyperparameter_search(model_name, backend_factory, OPTIMIZATION_METRIC)
    print(f'Melhor score em VAL para {model_name}: {best_score:.4f}')
    print(f'Melhores hiperparametros em {model_name}: {best_params}')
    final_artifact = train_final_model(model_name, backend_factory, best_params)
    save_json({'model_name': model_name, 'best_metric': final_artifact.best_metric, 'best_params': final_artifact.best_params, 'best_weights': str(final_artifact.best_weights)}, BEST_HYPERPARAMETERS_JSON.with_name(f"best_hyperparameters_{model_name.replace(' ', '_').lower()}.json"))
    return final_artifact


set_global_seed(42)
validate_dataset_yaml(dataset_yaml, CLASS_NAMES)
resolve_device()

artifacts: list[RunArtifacts] = []
summary_rows: list[dict[str, Any]] = []
for candidate_model in COMPARE_MODELS:
    result = run_model_workflow(candidate_model)
    artifacts.append(result)
    summary_rows.append({
        'Modelo': result.model_name,
        'Melhor_Metrica_VAL': result.best_metric,
        'Hiperparametros': json.dumps(result.best_params, ensure_ascii=False),
        'Peso': str(result.best_weights),
    })

ARTIFACTS_BY_MODEL = {artifact.model_name: artifact for artifact in artifacts}

best_artifact = max(artifacts, key=lambda item: item.best_metric)
_ensure_dir(ARTIFACTS_DIR)
shutil.copy2(best_artifact.best_weights, BEST_MODEL_PATH)
save_json({'model_name': best_artifact.model_name, 'best_metric': best_artifact.best_metric, 'best_params': best_artifact.best_params, 'best_weights': str(best_artifact.best_weights)}, BEST_HYPERPARAMETERS_JSON)
save_summary(summary_rows, TRAINING_SUMMARY_CSV)

print('Melhor Trial')
print(best_artifact.model_name)
print('Melhor Metrica de validacao')
print(best_artifact.best_metric)
print('Melhores Hiperparametros')
print(best_artifact.best_params)
print(f'Peso salvo em: {BEST_MODEL_PATH.resolve()}')
print(f'Summary salvo em: {TRAINING_SUMMARY_CSV.resolve()}')

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-06-12 00:20:38,666] A new study created in memory with name: no-name-44f8a736-a18c-40e7-b9b4-f7a21ad89f01

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0020360812711581913, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.9707665793723292, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_0, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adam, overlap_mask=True, patience=15, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_0, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0029314107754144394, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 1077.5313.5 MB/s, size: 476.9 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183 1.0Kit/s 0.2s.4s
train: New cache created: C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache
val: Fast image access  (ping: 0.10.0 ms, read: 991.3200.7 MB/s, size: 228.9 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19 747.0it/s 0.0s
val: New cache created: C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache
optimizer: Adam(lr=0.0020360812711581913, momentum=0.9707665793723292) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0029314107754144394), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_0\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_0
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      2.13G      2.318      10.74      1.666         23        640: 100% ━━━━━━━━━━━━ 23/23 1.1it/s 21.7s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.2it/s 1.7s4.9s
                   all         19        103      0.137     0.0844     0.0205     0.0115

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      1.99G      1.965      3.742      1.368         14        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.8s
                   all         19        103     0.0245     0.0951      0.024     0.0131

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      1.99G      1.829      3.305      1.351         12        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.6s
                   all         19        103     0.0268      0.235     0.0314     0.0134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      1.99G      1.951      2.911      1.379         14        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103        0.2      0.081     0.0517     0.0293

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      1.99G      1.843      2.957      1.378         16        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s1.4s
                   all         19        103     0.0409      0.162     0.0281     0.0178

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      1.99G      1.883      2.827      1.342         16        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.6s
                   all         19        103     0.0764      0.181     0.0585     0.0297

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      1.99G      1.821      2.633      1.342         16        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.538     0.0833      0.106     0.0753

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      1.99G      1.694       2.61      1.294         53        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.547      0.125      0.104     0.0642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      1.99G      1.777      2.545      1.279         72        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 13.9s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s1.4s
                   all         19        103      0.187      0.145     0.0963     0.0619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      1.99G      1.793      2.471      1.287         35        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.156      0.211      0.139     0.0773

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      1.99G      1.744      2.373      1.264         29        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.9it/s 0.7s1.9s
                   all         19        103      0.094      0.216      0.145     0.0784

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      1.99G      1.757      2.378      1.348         15        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.3s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.5s
                   all         19        103      0.417      0.202      0.179       0.11

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      1.99G      1.682      2.164      1.315         25        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 13.9s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.233      0.288      0.219      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      1.99G      1.751      2.122      1.261         39        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.6s
                   all         19        103      0.217      0.286      0.211      0.127

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      1.99G      1.693        2.2      1.239         10        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.5it/s 0.8s2.3s
                   all         19        103      0.512      0.222      0.192      0.103

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      1.99G      1.727      2.084      1.207         44        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.9it/s 0.7s1.9s
                   all         19        103      0.364      0.259      0.189      0.112

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      1.99G      1.659      2.157      1.261         10        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.197      0.382      0.219      0.124

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      1.99G      1.617      1.875      1.222         20        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.204      0.325      0.251      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      1.99G      1.705      2.025      1.211         45        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.204      0.326      0.236      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      1.99G      1.593      1.974      1.177         48        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.6s
                   all         19        103      0.206      0.368      0.244      0.138

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      1.99G      1.552       1.95      1.191         21        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.7s
                   all         19        103      0.353      0.474      0.272      0.159

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      1.99G      1.575      1.795        1.2         24        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.6s
                   all         19        103      0.396      0.429      0.316       0.19

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      1.99G      1.546      1.742      1.167         28        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.535      0.266      0.336      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      1.99G      1.603      1.803      1.206         37        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.584       0.26      0.311      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      1.99G      1.615      1.726      1.156         49        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.271      0.333      0.301      0.186

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      1.99G      1.529      1.729      1.175         18        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.343      0.291      0.267      0.162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      1.99G       1.55      1.632      1.169         35        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.266      0.365      0.254      0.158

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      1.99G      1.566      1.697      1.243         58        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.6s
                   all         19        103      0.264      0.345      0.263      0.164

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      1.99G      1.472      1.529      1.205         31        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.5s
                   all         19        103       0.29      0.314      0.302      0.188

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      1.99G      1.519      1.591      1.211         52        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.303      0.332       0.32      0.197

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      1.99G      1.537      1.581      1.199         21        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.7s
                   all         19        103      0.293      0.352      0.315      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      1.99G      1.479      1.599      1.164         33        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.3s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.331        0.4      0.321      0.193

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      1.99G      1.489      1.495      1.154         27        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.342      0.399      0.336      0.206

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      1.99G      1.518      1.512      1.181         60        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.5s
                   all         19        103      0.428      0.429      0.324      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      1.99G      1.498      1.614      1.154         12        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s

[I 2026-06-12 00:40:36,166] Trial 0 finished with value: 0.38637304351991897 and parameters: {'epochs': 100, 'batch_size': 8, 'learning_rate': 0.0020360812711581913, 'weight_decay': 0.0029314107754144394, 'optimizer': 'Adam', 'img_size': 640, 'momentum': 0.9707665793723292, 'scheduler': 'step', 'patience': 15}. Best is trial 0 with value: 0.38637304351991897.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=80, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0022984631761375825, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8109160923867552, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_1, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_1, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0012386046016817083, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 1238.5290.6 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 1048.7329.4 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: AdamW(lr=0.0022984631761375825, momentum=0.8109160923867552) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0012386046016817083), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_1\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_1
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/80      1.62G      2.429      9.502      1.612         23        512: 100% ━━━━━━━━━━━━ 23/23 1.4it/s 16.2s0.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.6s
                   all         19        103      0.436      0.179     0.0959     0.0523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/80      1.62G      2.033      3.653      1.264         14        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 10.1s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.0it/s 0.5s1.4s
                   all         19        103      0.436      0.109     0.0953     0.0435

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/80      1.62G       1.86      3.219      1.251         12        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.239     0.0139    0.00593     0.0034

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/80      1.62G       2.01       3.18      1.259         14        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.3it/s 0.5s1.2s
                   all         19        103     0.0131     0.0694    0.00195   0.000508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/80      1.62G      2.059      3.175      1.364         16        512: 100% ━━━━━━━━━━━━ 23/23 2.1it/s 10.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s1.2s
                   all         19        103      0.117     0.0412     0.0616      0.036

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/80      1.62G      1.956       3.14      1.264         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.6it/s 0.8s2.0s
                   all         19        103    0.00111      0.119   0.000569   0.000195

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/80      1.62G       1.92      3.111      1.261         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.5s
                   all         19        103    0.00558     0.0433    0.00133   0.000726

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/80      1.62G      1.799      2.885      1.187         53        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.2it/s 0.5s1.2s
                   all         19        103      0.428     0.0782     0.0945     0.0649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/80      1.62G      1.869       2.67      1.215         72        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.5s1.2s
                   all         19        103      0.333      0.252      0.176     0.0997

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/80      1.62G      1.846      2.636      1.202         35        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.1it/s 0.5s1.2s
                   all         19        103      0.487      0.218      0.128     0.0689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/80      1.62G      1.818      2.466      1.184         29        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103       0.26      0.241      0.211      0.132

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/80      1.62G      1.709      2.424      1.194         15        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.5s1.2s
                   all         19        103      0.584      0.307       0.22       0.13

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/80      1.62G      1.678       2.25      1.168         25        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.247       0.29      0.189      0.117

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/80      1.62G      1.693      2.039      1.124         39        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.246      0.241      0.194      0.122

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/80      1.62G      1.704      2.074      1.136         10        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.529        0.3      0.248      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/80      1.62G       1.69      1.973      1.092         44        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 10.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.4s1.2s
                   all         19        103      0.304      0.299      0.234      0.139

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/80      1.62G       1.64      2.028      1.143         10        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.421      0.337      0.269      0.166

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/80      1.62G      1.579      1.829      1.091         20        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.4s1.2s
                   all         19        103      0.446      0.272      0.265      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/80      1.62G      1.702       1.94      1.096         45        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.2s
                   all         19        103      0.108      0.622      0.235      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/80      1.62G       1.56      1.813      1.084         48        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.379      0.307      0.291      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/80      1.62G      1.517      1.819      1.087         21        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.493      0.373      0.333      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/80      1.62G      1.558      1.758      1.103         24        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.2s
                   all         19        103      0.283      0.337      0.294      0.166

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/80      1.62G       1.49      1.684      1.067         28        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.4s1.2s
                   all         19        103      0.567      0.308      0.295       0.19

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/80      1.62G      1.539      1.685      1.079         37        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103       0.28      0.382      0.311      0.196

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/80      1.62G      1.576      1.617      1.044         49        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.257      0.368      0.269      0.168

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/80      1.62G       1.46      1.611      1.054         18        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.249      0.396      0.279      0.172

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/80      1.62G      1.487       1.53      1.055         35        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.3s
                   all         19        103       0.42      0.372       0.32       0.19

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/80      1.62G      1.521      1.593       1.07         58        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.2it/s 0.5s1.2s
                   all         19        103      0.414      0.395      0.283      0.152

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/80      1.62G      1.458      1.453      1.089         31        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.4s1.2s
                   all         19        103      0.214      0.294      0.264      0.158

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/80      1.62G      1.557      1.548      1.117         52        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s1.1s
                   all         19        103      0.292      0.363      0.313      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/80      1.62G      1.609      1.561      1.111         21        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s1.2s
                   all         19        103      0.485      0.356      0.323      0.188

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/80      1.62G      1.433      1.469      1.068         33        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.3it/s 0.5s1.2s
                   all         19        103       0.25      0.399      0.289      0.181

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/80      1.62G      1.428      1.412      1.054         27        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s1.2s
                   all         19        103      0.229      0.389      0.292       0.18

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/80      1.62G      1.463      1.412       1.08         59        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.341      0.413      0.305      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/80      1.62G      1.435      1.433      1.041         12        512: 100% ━━━━━━━━━━━━ 23/23 2.3it/s 9.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.3it/s 0.5s1.2s
                   all         19        103      0.372      0.439      0.307      0.193


[I 2026-06-12 00:55:04,556] Trial 1 finished with value: 0.3840744846412368 and parameters: {'epochs': 80, 'batch_size': 8, 'learning_rate': 0.0022984631761375825, 'weight_decay': 0.0012386046016817083, 'optimizer': 'AdamW', 'img_size': 512, 'momentum': 0.8109160923867552, 'scheduler': 'onecycle', 'patience': 30}. Best is trial 0 with value: 0.38637304351991897.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=120, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0009885477189256258, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8765697627073381, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_2, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0001010433394006205, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 159.928.6 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 939.6412.6 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: AdamW(lr=0.0009885477189256258, momentum=0.8765697627073381) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0001010433394006205), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_2\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_2
Starting training for 120 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/120      1.69G      2.438      9.601      1.624         23        512: 100% ━━━━━━━━━━━━ 23/23 2.1it/s 10.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.8s
                   all         19        103      0.499     0.0625     0.0561     0.0254

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/120      1.69G      2.051      3.638      1.295         14        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s1.2s
                   all         19        103      0.293      0.163      0.138      0.085

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/120      1.69G      1.842      3.015      1.234         12        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103       0.54      0.107      0.097     0.0344

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/120      1.69G      1.937      2.882      1.226         14        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.1it/s 0.4s1.0s
                   all         19        103      0.318      0.267      0.222       0.12

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/120      1.69G      1.779      2.609      1.208         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s1.1s
                   all         19        103       0.17      0.188      0.187       0.11

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/120      1.69G      1.767        2.6      1.195         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.378      0.184      0.159     0.0946

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/120      1.69G       1.78      2.368      1.193         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103       0.24      0.262      0.178     0.0962

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/120      1.69G      1.609      2.207       1.12         53        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103       0.25      0.295      0.233      0.137

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/120      1.69G      1.628      2.035       1.11         72        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.191      0.286      0.206      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/120      1.69G      1.705      2.024       1.14         35        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.353      0.385       0.24      0.151

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/120      1.69G      1.669       1.99      1.112         29        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.289      0.321      0.266      0.154

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/120      1.69G      1.567      1.961      1.138         15        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.415      0.417      0.246      0.141

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/120      1.69G      1.563      1.959      1.117         25        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.198      0.307      0.213       0.13

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/120      1.69G       1.58       1.69      1.078         39        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s1.0s
                   all         19        103      0.398      0.313      0.286      0.176

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/120      1.69G      1.543       1.69      1.089         10        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.487      0.356      0.274      0.164

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/120      1.69G      1.559      1.629      1.053         44        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103       0.42      0.261      0.284      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/120      1.69G      1.544      1.636      1.093         10        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.289      0.394      0.309      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/120      1.69G      1.484       1.52      1.063         20        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s1.0s
                   all         19        103      0.381      0.279      0.297      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/120      1.69G      1.583      1.593      1.063         45        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.329      0.366      0.312      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/120      1.69G      1.436      1.469      1.034         48        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.4s1.1s
                   all         19        103       0.41      0.389      0.307      0.191

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/120      1.69G      1.418      1.478      1.046         21        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.403      0.417      0.312      0.193

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/120      1.69G      1.431      1.356      1.053         24        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.358      0.391      0.342      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/120      1.69G      1.395      1.347      1.034         28        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.506      0.358      0.351      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/120      1.69G      1.439      1.339      1.044         37        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.437      0.418      0.348      0.204

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/120      1.69G      1.487      1.349      1.023         49        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s1.0s
                   all         19        103      0.436      0.396      0.335      0.185

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/120      1.69G      1.397      1.338      1.038         18        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103       0.27      0.367      0.319      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/120      1.69G       1.37       1.24      1.015         35        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s1.1s
                   all         19        103      0.263      0.358      0.288      0.175

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/120      1.69G      1.454      1.374      1.057         58        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.415      0.374      0.308      0.187

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/120      1.69G       1.36      1.261      1.062         31        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.329      0.415      0.333        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/120      1.69G      1.415       1.25      1.065         52        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.319      0.382      0.323      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/120      1.69G      1.429      1.249       1.06         21        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103        0.3      0.407      0.331      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/120      1.69G      1.324      1.217      1.025         33        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.318      0.343      0.321      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/120      1.69G       1.29      1.195     0.9996         27        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.294      0.424      0.329      0.198

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/120      1.69G      1.361      1.232      1.045         59        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s1.1s
                   all         19        103      0.418      0.461      0.324      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/120      1.69G      1.349      1.276      1.018         12        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.402       0.39       0.35      0.226


[I 2026-06-12 01:11:30,795] Trial 2 finished with value: 0.3987440397835331 and parameters: {'epochs': 120, 'batch_size': 8, 'learning_rate': 0.0009885477189256258, 'weight_decay': 0.0001010433394006205, 'optimizer': 'AdamW', 'img_size': 512, 'momentum': 0.8765697627073381, 'scheduler': 'step', 'patience': 30}. Best is trial 2 with value: 0.3987440397835331.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=60, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=1.2538623333170825e-05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8577339205866112, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_3, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0029863696007403667, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.1 ms, read: 614.6291.9 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 1200.4361.8 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: AdamW(lr=1.2538623333170825e-05, momentum=0.8577339205866112) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0029863696007403667), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_3\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_3
Starting training for 60 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/60      1.41G       2.52      8.424      1.617         11        512: 100% ━━━━━━━━━━━━ 46/46 3.2it/s 14.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.6it/s 0.5s0.4s
                   all         19        103   0.000697     0.0139   0.000255   0.000101

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/60      1.41G      2.326       4.93      1.398          3        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103    0.00756      0.155    0.00858    0.00415

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/60      1.41G      2.067      4.314       1.29          8        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103    0.00348      0.252     0.0137    0.00667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/60      1.41G      2.194      4.395      1.344         13        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.3s
                   all         19        103    0.00383      0.291     0.0125    0.00622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/60      1.41G      2.122      4.261      1.361          7        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103    0.00432      0.314     0.0186    0.00947

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/60      1.41G      2.157      4.124      1.312          8        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103    0.00481      0.328     0.0289     0.0155

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/60      1.41G       2.12      3.985      1.313         13        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.473     0.0423     0.0323     0.0172

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/60      1.41G      1.956      4.019      1.316         12        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s0.3s
                   all         19        103    0.00764      0.316     0.0422     0.0231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/60      1.41G      2.093      3.802      1.326         11        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.618     0.0888     0.0515     0.0284

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/60      1.41G      1.985      3.753      1.282          4        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.612     0.0363     0.0653     0.0362

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/60      1.41G      2.053      3.846      1.295         17        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.4s
                   all         19        103      0.624     0.0673     0.0716     0.0417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/60      1.41G      1.984       3.59      1.285         12        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.626     0.0745     0.0766     0.0455

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/60      1.41G      2.021      3.804        1.3          2        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.4s
                   all         19        103      0.741     0.0842     0.0812      0.047

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/60      1.41G      2.018      3.604      1.257         34        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.755     0.0951      0.101     0.0601

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/60      1.41G       2.03      3.551      1.317          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.773      0.102      0.112      0.066

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/60      1.41G       2.12       3.64      1.277          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103       0.77     0.0951      0.116      0.068

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/60      1.41G      1.885      3.319      1.237          7        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103       0.76     0.0951      0.115      0.066

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/60      1.41G      2.056      3.371      1.274         18        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.775     0.0951      0.118     0.0668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/60      1.41G      1.938      3.471      1.259          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.775     0.0951      0.122     0.0694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/60      1.41G      1.965      3.246      1.211          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.4it/s 0.6s0.4s
                   all         19        103      0.776     0.0951      0.127     0.0706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/60      1.41G      2.092      3.495       1.25         31        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.4s
                   all         19        103       0.77     0.0951      0.122       0.07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/60      1.41G      2.001      3.277      1.237          9        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.769     0.0978      0.128     0.0718

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/60      1.41G      2.021      3.253       1.28          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.3s
                   all         19        103      0.567      0.131       0.14      0.077

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/60      1.41G       1.92      3.223       1.24         14        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.529      0.124      0.135     0.0784

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/60      1.41G      1.873      2.969       1.24          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.411      0.126      0.136     0.0764

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/60      1.41G      1.821      3.192      1.216          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.404      0.124      0.139      0.078

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/60      1.41G      1.854      2.972      1.234         21        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.456      0.163      0.141     0.0804

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/60      1.41G      1.881      3.244      1.265          9        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.5s0.4s
                   all         19        103       0.39      0.188      0.154     0.0868

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/60      1.41G      1.931      3.193      1.263          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.378      0.188      0.151     0.0838

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/60      1.41G      1.905      3.131      1.247          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.378      0.188      0.144     0.0804

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/60      1.41G      1.925      3.172      1.225         14        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103       0.37      0.186      0.159     0.0912

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/60      1.41G      1.819      3.072      1.228          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.384      0.186      0.164     0.0914

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/60      1.41G      1.846      2.988      1.211          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.374      0.186      0.165     0.0928

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/60      1.41G      1.845       2.91      1.215         30        512: 100% ━━━━━━━━━━━━ 46/46 3.6it/s 12.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.6it/s 0.5s0.4s
                   all         19        103      0.392      0.186      0.153     0.0843

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/60      1.41G      1.897      2.973      1.222         11        512: 100% ━━━━━━━━━━━━ 46/46 3.4it/s 13.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.3it/s 0.5s0.4s
                   all         19        103      0.382      0.186      0.148     0.0826


[I 2026-06-12 01:27:38,566] Trial 3 finished with value: 0.1890329820484727 and parameters: {'epochs': 60, 'batch_size': 4, 'learning_rate': 1.2538623333170825e-05, 'weight_decay': 0.0029863696007403667, 'optimizer': 'AdamW', 'img_size': 512, 'momentum': 0.8577339205866112, 'scheduler': 'step', 'patience': 30}. Best is trial 2 with value: 0.3987440397835331.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=90, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005794457860851689, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.9712476616320388, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_4, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.004305364756051902, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.1 ms, read: 163.827.1 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 1130.1335.2 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: AdamW(lr=0.0005794457860851689, momentum=0.9712476616320388) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.004305364756051902), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_4\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_4
Starting training for 90 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/90       1.3G      2.463      8.091      1.575         11        512: 100% ━━━━━━━━━━━━ 46/46 3.2it/s 14.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.451     0.0208    0.00694    0.00365

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/90       1.3G      2.309      4.486      1.369          3        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0it/s 0.5s0.4s
                   all         19        103      0.833      0.106     0.0799     0.0435

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/90       1.3G       1.96      3.548      1.241          8        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9it/s 0.5s0.4s
                   all         19        103      0.505      0.134     0.0668     0.0309

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/90       1.3G      2.026      3.408      1.289         13        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.198      0.223      0.177       0.11

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/90       1.3G      1.804       3.14      1.229          7        512: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.2it/s 0.4s0.3s
                   all         19        103       0.65      0.225        0.2      0.133

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/90       1.3G      1.892      2.847      1.202          8        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.295      0.179      0.184      0.117

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/90       1.3G      1.717       2.56       1.17         13        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 11.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.293      0.177      0.216      0.131

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/90       1.3G      1.691      2.653      1.244         12        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.231      0.159      0.207      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/90       1.3G      1.772      2.505        1.2         11        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.499      0.263      0.222       0.14

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/90       1.3G      1.626      2.388      1.141          4        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.395      0.264      0.238      0.155

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/90       1.3G      1.687      2.274      1.144         17        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.288      0.332       0.26      0.153

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/90       1.3G      1.686      2.146      1.153         12        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.239      0.334      0.251      0.146

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/90       1.3G      1.567      2.228      1.143          2        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.237      0.326      0.232      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/90       1.3G      1.631      2.091      1.124         34        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.236      0.257      0.203      0.129

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/90       1.3G      1.572      1.951      1.136          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.271      0.266      0.199      0.129

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/90       1.3G      1.664      1.991      1.122          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.193      0.353      0.224      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/90       1.3G      1.508      1.748        1.1          7        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.202      0.322      0.225      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/90       1.3G      1.549      1.794      1.095         18        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.5s0.4s
                   all         19        103      0.242      0.384      0.251       0.16

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/90       1.3G      1.541      1.793      1.096          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.271      0.416      0.285      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/90       1.3G      1.535      1.664      1.076          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.255      0.379      0.288      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/90       1.3G      1.562      1.789      1.075         31        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.253      0.393      0.277      0.168

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/90       1.3G      1.582      1.639      1.103          9        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.428      0.337      0.297      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/90       1.3G      1.491      1.538      1.076          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103       0.32      0.381      0.328      0.211

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/90       1.3G      1.483      1.653      1.072         14        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.291      0.376      0.331      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/90       1.3G      1.375      1.382       1.07          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.3s
                   all         19        103      0.291      0.419      0.341      0.211

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/90       1.3G      1.354      1.419      1.055          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.269      0.368      0.346      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/90       1.3G      1.425       1.44      1.078         21        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s0.3s
                   all         19        103       0.49      0.335      0.357       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/90       1.3G      1.369      1.538      1.053          9        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.3s
                   all         19        103      0.244      0.396      0.336      0.204

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/90       1.3G      1.419      1.469      1.064          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.254      0.345      0.314      0.196

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/90       1.3G       1.42      1.385      1.075          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.8it/s 0.5s0.4s
                   all         19        103      0.308       0.29      0.315      0.201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/90       1.3G      1.499      1.581      1.074         14        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.308      0.308      0.328      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/90       1.3G      1.377      1.451      1.062          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.293      0.323      0.343       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/90       1.3G      1.341      1.306      1.053          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103       0.27      0.419      0.345      0.213

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/90       1.3G      1.362      1.258      1.037         30        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.254      0.438       0.34       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/90       1.3G      1.446      1.338      1.064         11        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.245      0.417       0.34      0.207


[I 2026-06-12 01:47:21,433] Trial 4 finished with value: 0.34801371114694946 and parameters: {'epochs': 90, 'batch_size': 4, 'learning_rate': 0.0005794457860851689, 'weight_decay': 0.004305364756051902, 'optimizer': 'AdamW', 'img_size': 512, 'momentum': 0.9712476616320388, 'scheduler': 'step', 'patience': 30}. Best is trial 2 with value: 0.3987440397835331.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=110, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=2.318990902483841e-05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8237918474832903, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_5, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adam, overlap_mask=True, patience=15, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0022183114950758754, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.20.2 ms, read: 159.641.3 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 1084.3373.6 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: Adam(lr=2.318990902483841e-05, momentum=0.8237918474832903) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0022183114950758754), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_5\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_5
Starting training for 110 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/110      1.32G      2.495      8.413       1.61         11        512: 100% ━━━━━━━━━━━━ 46/46 3.4it/s 13.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.8it/s 0.5s0.4s
                   all         19        103    0.00102     0.0486   0.000254   8.93e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/110      1.32G      2.326      4.991      1.404          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0it/s 0.5s0.4s
                   all         19        103      0.229     0.0705     0.0203     0.0134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/110      1.32G      2.059      4.235      1.293          8        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s0.3s
                   all         19        103    0.00619       0.38     0.0352     0.0188

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/110      1.32G      2.187      4.241      1.351         13        512: 100% ━━━━━━━━━━━━ 46/46 3.9it/s 11.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.4s
                   all         19        103    0.00694       0.39     0.0555     0.0302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/110      1.32G      2.089      4.032      1.355          7        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.1it/s 0.4s0.3s
                   all         19        103     0.0495      0.202     0.0618     0.0318

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/110      1.32G      2.123      3.875      1.287          8        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.731     0.0607     0.0719     0.0376

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/110      1.32G      2.072       3.61      1.301         13        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.737     0.0615      0.079     0.0431

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/110      1.32G      1.942      3.646      1.313         12        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103       0.76     0.0812      0.093     0.0518

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/110      1.32G      2.016      3.437      1.292         11        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.765     0.0812      0.103     0.0562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/110      1.32G      1.899       3.36      1.239          4        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.761     0.0881      0.111     0.0625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/110      1.32G      1.981      3.391       1.27         17        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.526      0.107       0.12     0.0668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/110      1.32G      1.895      3.139      1.242         12        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.341      0.115      0.136     0.0756

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/110      1.32G      1.922      3.357      1.277          2        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.267      0.126      0.137     0.0747

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/110      1.32G      1.909      3.102      1.202         34        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.286      0.152      0.141     0.0765

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/110      1.32G      1.895      3.023      1.262          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.271      0.172      0.152     0.0828

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/110      1.32G      2.006      3.126      1.228          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103       0.39      0.172      0.157     0.0875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/110      1.32G      1.747      2.772      1.175          7        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.415      0.182      0.156     0.0863

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/110      1.32G      1.905      2.805      1.214         18        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.416      0.215      0.163     0.0896

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/110      1.32G      1.822          3      1.202          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.407      0.184      0.165     0.0932

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/110      1.32G      1.832      2.755      1.164          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s0.3s
                   all         19        103       0.33      0.214      0.177     0.0997

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/110      1.32G      1.954      2.901      1.197         31        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.318      0.206      0.169      0.095

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/110      1.32G      1.824      2.679      1.167          9        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.315      0.233      0.182      0.101

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/110      1.32G      1.858      2.628       1.21          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.412      0.234      0.193      0.105

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/110      1.32G      1.799      2.603      1.186         14        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.4s
                   all         19        103       0.35      0.246      0.194      0.107

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/110      1.32G      1.761      2.369      1.181          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.328      0.241      0.192      0.106

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/110      1.32G       1.66      2.544      1.144          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s0.3s
                   all         19        103      0.224      0.253      0.204      0.112

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/110      1.32G      1.734      2.359      1.191         21        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103       0.32      0.238      0.204      0.116

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/110      1.32G      1.723      2.548      1.186          9        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.341      0.254      0.211      0.116

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/110      1.32G      1.722      2.589       1.17          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.242      0.277      0.211      0.116

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/110      1.32G      1.715      2.418       1.16          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.265      0.253      0.212      0.119

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/110      1.32G      1.766      2.544      1.158         14        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.439      0.226      0.227      0.132

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/110      1.32G      1.652       2.39      1.152          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.5s0.4s
                   all         19        103      0.248      0.232      0.231      0.132

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/110      1.32G      1.674      2.295      1.136          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.216      0.291      0.235      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/110      1.32G      1.643      2.178      1.134         30        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.225      0.291      0.231      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/110      1.32G      1.749      2.249      1.157         11        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s0.3s
                   all         19        103      0.228      0.277      0.232       0.13


[I 2026-06-12 02:04:56,656] Trial 5 finished with value: 0.27758837846318346 and parameters: {'epochs': 110, 'batch_size': 4, 'learning_rate': 2.318990902483841e-05, 'weight_decay': 0.0022183114950758754, 'optimizer': 'Adam', 'img_size': 512, 'momentum': 0.8237918474832903, 'scheduler': 'onecycle', 'patience': 15}. Best is trial 2 with value: 0.3987440397835331.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=70, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001063301528375544, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8492396375993807, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_6, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=15, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0018454261508903287, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 171.720.7 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 1060.8296.5 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: SGD(lr=0.001063301528375544, momentum=0.8492396375993807) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0018454261508903287), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_6\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_6
Starting training for 70 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/70      2.35G      2.478      15.19      1.767         23        640: 100% ━━━━━━━━━━━━ 23/23 1.4it/s 16.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.0it/s 1.0s2.9s
                   all         19        103          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/70      1.92G      2.329      8.228      1.587         14        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.9s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.8it/s 0.7s2.0s
                   all         19        103          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/70      1.92G      2.162      6.394      1.583         12        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.7s
                   all         19        103          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/70      1.92G      2.217      5.345      1.536         14        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.9s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.6s
                   all         19        103    0.00525     0.0155    0.00688     0.0035

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/70      1.92G       2.05      4.922      1.489         16        640: 100% ━━━━━━━━━━━━ 23/23 1.7it/s 13.8s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.6s
                   all         19        103      0.576     0.0769     0.0312     0.0149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/70      1.92G       2.04      4.662      1.437         16        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.6s
                   all         19        103      0.516     0.0994     0.0541     0.0241

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/70      2.24G      2.066      4.162      1.479         16        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 13.9s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.7s
                   all         19        103      0.554     0.0945     0.0822     0.0379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/70      1.91G      1.899      3.863      1.396         53        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.542      0.101      0.101     0.0539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/70      1.91G      1.943      3.786      1.391         72        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.547      0.122      0.126     0.0712

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/70      2.02G      1.913      3.378      1.342         35        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.8it/s 0.7s2.0s
                   all         19        103      0.339      0.165      0.147     0.0838

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/70      1.88G      1.865      3.193      1.322         29        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.357      0.202      0.169     0.0957

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/70         2G      1.755      3.219      1.342         15        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.386      0.204      0.181      0.103

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/70         2G      1.758      3.068      1.347         25        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s1.4s
                   all         19        103      0.315      0.246      0.198      0.114

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/70         2G      1.755      2.743      1.276         39        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.4s
                   all         19        103      0.305      0.217      0.206      0.118

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/70         2G      1.782      2.707      1.285         10        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s1.4s
                   all         19        103      0.236      0.285      0.217      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/70         2G      1.744      2.488      1.229         44        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.5s1.4s
                   all         19        103      0.272      0.283      0.223      0.128

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/70         2G      1.727      2.477      1.306         10        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.5s
                   all         19        103      0.276      0.316      0.233      0.133

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/70         2G      1.645       2.37      1.238         20        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.291      0.324      0.239      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/70         2G      1.767      2.382      1.252         45        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.5s1.4s
                   all         19        103      0.284      0.337      0.247      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/70         2G       1.67      2.317      1.234         48        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.292      0.367      0.271      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/70         2G      1.608      2.189      1.216         21        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.283      0.357       0.28      0.166

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/70         2G      1.649      2.173       1.23         24        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s1.4s
                   all         19        103      0.293      0.365      0.281      0.167

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/70         2G      1.596      2.087      1.191         28        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s1.4s
                   all         19        103      0.312      0.375       0.28      0.168

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/70         2G      1.605      2.016      1.208         37        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.5s1.5s
                   all         19        103      0.316      0.348      0.265      0.161

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/70         2G      1.717      2.067      1.199         49        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s1.5s
                   all         19        103      0.319      0.324      0.262      0.162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/70         2G      1.584      2.018      1.197         18        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.5s
                   all         19        103      0.306      0.345      0.269      0.167

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/70         2G      1.571      1.998      1.184         35        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.293       0.38      0.279      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/70         2G      1.579      1.953      1.226         58        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s1.4s
                   all         19        103       0.29      0.353      0.284      0.177

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/70         2G      1.538      1.899      1.226         31        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.5s1.5s
                   all         19        103      0.285      0.341      0.284      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/70         2G      1.604      1.839      1.248         52        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.276      0.376       0.29      0.178

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/70         2G      1.639      1.911      1.256         21        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s1.4s
                   all         19        103      0.305      0.389      0.313      0.195

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/70         2G      1.483      1.855      1.171         33        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s1.4s
                   all         19        103      0.287       0.35      0.295      0.187

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/70         2G      1.484      1.714      1.155         27        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s1.4s
                   all         19        103      0.316      0.411      0.296      0.186

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/70         2G      1.538      1.724       1.21         60        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s1.4s
                   all         19        103      0.326       0.42      0.299      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/70         2G      1.559      1.761      1.191         12        640: 100% ━━━━━━━━━━━━ 23/23 1.6it/s 14.1s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s1.5s
                   all         19        103      0.441      0.409        0.3      0.186


[I 2026-06-12 02:22:18,486] Trial 6 finished with value: 0.32525505389949216 and parameters: {'epochs': 70, 'batch_size': 8, 'learning_rate': 0.001063301528375544, 'weight_decay': 0.0018454261508903287, 'optimizer': 'SGD', 'img_size': 640, 'momentum': 0.8492396375993807, 'scheduler': 'onecycle', 'patience': 15}. Best is trial 2 with value: 0.3987440397835331.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=120, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0033195486668939774, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8750652546528781, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_7, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adam, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.00015846215142993947, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 183.114.8 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 1066.6419.3 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: Adam(lr=0.0033195486668939774, momentum=0.8750652546528781) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.00015846215142993947), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_7\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_7
Starting training for 120 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/120       1.9G      2.496      7.733      1.594         11        512: 100% ━━━━━━━━━━━━ 46/46 3.0it/s 15.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.4it/s 0.9s0.7s
                   all         19        103      0.224     0.0684    0.00275   0.000911

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/120       1.9G      2.358      4.557      1.423          3        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.5s
                   all         19        103      0.028     0.0208    0.00724    0.00145

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/120       1.9G      2.357      3.746      1.432          8        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.6it/s 0.8s0.7s
                   all         19        103          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/120       1.9G      2.348      3.769      1.429         13        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.7it/s 0.5s0.4s
                   all         19        103          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/120       1.9G      2.255       3.67      1.462          7        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.3it/s 0.6s0.5s
                   all         19        103   5.07e-05     0.0171   7.88e-06   2.15e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/120       1.9G      2.373      3.701      1.394          8        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.8it/s 0.6s0.5s
                   all         19        103     0.0113      0.156     0.0139    0.00352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/120       1.9G      2.159      3.371      1.365         13        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.1it/s 0.5s0.4s
                   all         19        103      0.209       0.21      0.103      0.065

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/120       1.9G      2.038      3.258      1.392         12        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.3s
                   all         19        103      0.802      0.181      0.176     0.0921

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/120       1.9G       2.06      3.168      1.333         11        512: 100% ━━━━━━━━━━━━ 46/46 3.6it/s 13.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.575      0.161      0.145     0.0889

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/120       1.9G      1.937      3.006      1.276          4        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.552       0.26      0.129     0.0733

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/120       1.9G      1.937      2.853      1.277         17        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.503      0.257      0.186      0.106

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/120       1.9G       1.91      2.737      1.273         12        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.312      0.337      0.214      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/120       1.9G      1.782      2.804      1.265          2        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.493      0.234      0.225      0.132

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/120       1.9G      1.833      2.768      1.207         34        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.522       0.26       0.24      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/120       1.9G      1.789      2.552      1.221          3        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.553      0.267      0.253      0.165

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/120       1.9G      1.825      2.697      1.177          3        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.271       0.24      0.221      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/120       1.9G      1.761       2.46      1.212          7        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.459       0.28      0.233      0.141

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/120       1.9G      1.752      2.266      1.197         18        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.299      0.277      0.264       0.15

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/120       1.9G      1.801      2.485       1.19          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.255      0.248      0.221       0.14

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/120       1.9G      1.736      2.114      1.143          5        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.5s0.4s
                   all         19        103      0.569      0.278      0.226      0.137

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/120       1.9G      1.775      2.277      1.138         31        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103      0.212      0.301       0.22      0.129

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/120       1.9G      1.757      2.223       1.18          9        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.366      0.306      0.252      0.154

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/120       1.9G       1.67      1.994      1.163          3        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s0.4s
                   all         19        103      0.357      0.356      0.244      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/120       1.9G      1.644      2.073      1.119         14        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.305      0.261      0.216      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/120       1.9G       1.59      1.826      1.148          3        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.352      0.317      0.224      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/120       1.9G      1.575       1.97      1.119          5        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.572       0.25      0.276      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/120       1.9G      1.592      1.879      1.141         21        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.217      0.315      0.223      0.145

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/120       1.9G      1.541      1.917      1.125          9        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.285      0.324      0.293      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/120       1.9G      1.558      2.037      1.118          6        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.369      0.288      0.268      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/120       1.9G      1.553      1.924       1.13          5        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s0.4s
                   all         19        103      0.212      0.287      0.263      0.159

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/120       1.9G      1.623      2.042      1.115         14        512: 100% ━━━━━━━━━━━━ 46/46 3.7it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s0.4s
                   all         19        103      0.309      0.305      0.227      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/120       1.9G      1.613      2.011      1.147          5        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.404      0.277       0.26      0.152

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/120       1.9G      1.586      1.813       1.13          6        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s0.4s
                   all         19        103      0.258      0.322      0.273      0.169

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/120       1.9G      1.546      1.679      1.107         30        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s0.4s
                   all         19        103      0.287      0.306      0.271      0.169

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/120       1.9G      1.622      1.875      1.128         11        512: 100% ━━━━━━━━━━━━ 46/46 3.8it/s 12.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s0.3s
                   all         19        103       0.37      0.292      0.293      0.171


[I 2026-06-12 02:40:35,184] Trial 7 finished with value: 0.36494712671713714 and parameters: {'epochs': 120, 'batch_size': 4, 'learning_rate': 0.0033195486668939774, 'weight_decay': 0.00015846215142993947, 'optimizer': 'Adam', 'img_size': 512, 'momentum': 0.8750652546528781, 'scheduler': 'cosine', 'patience': 20}. Best is trial 2 with value: 0.3987440397835331.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0007264257237865342, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8736991804426751, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_8, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_8, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0030161343547410197, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 83.841.1 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 822.4407.5 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: AdamW(lr=0.0007264257237865342, momentum=0.8736991804426751) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0030161343547410197), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_8\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_8
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      1.47G      2.262      8.086      1.596         11        640: 100% ━━━━━━━━━━━━ 46/46 2.3it/s 19.6s0.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.9it/s 0.8s0.6s
                   all         19        103      0.471      0.109      0.058      0.032

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      1.47G       2.03      4.641      1.383          3        640: 100% ━━━━━━━━━━━━ 46/46 2.6it/s 17.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103     0.0201      0.423     0.0752     0.0487

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      1.47G      1.774      3.208      1.276          8        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.5s
                   all         19        103      0.342      0.214      0.144       0.07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      1.47G        1.8      3.126      1.288         13        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.3it/s 0.6s0.5s
                   all         19        103      0.257      0.219      0.197      0.113

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      1.47G      1.634      2.941      1.278          7        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.246      0.202      0.171     0.0891

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20      1.47G      1.789      2.517       1.26          8        640: 100% ━━━━━━━━━━━━ 46/46 2.4it/s 19.1s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.4it/s 0.9s0.7s
                   all         19        103      0.178      0.249      0.193      0.112

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      1.47G      1.629      2.221      1.233         13        640: 100% ━━━━━━━━━━━━ 46/46 2.6it/s 17.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.3it/s 0.6s0.5s
                   all         19        103        0.2      0.333      0.245      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20      1.47G      1.529      2.211      1.252         12        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.1it/s 0.6s0.5s
                   all         19        103      0.301      0.334      0.263       0.16

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      1.47G      1.628       2.16      1.253         11        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103      0.645      0.262      0.266       0.16

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20      1.47G      1.473      1.923      1.159          4        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103      0.254      0.321      0.271       0.16
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20      1.47G      1.472      1.825      1.237         17        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.5it/s 0.5s0.4s
                   all         19        103      0.557      0.269      0.257      0.161

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20      1.47G      1.474      1.685      1.237          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.4it/s 0.6s0.4s
                   all         19        103       0.27      0.349      0.302       0.19

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20      1.47G       1.46      1.622      1.202          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.5s
                   all         19        103      0.494      0.368      0.345      0.213

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20      1.47G      1.469      1.566      1.237          3        640: 100% ━━━━━━━━━━━━ 46/46 2.0it/s 22.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.5s
                   all         19        103      0.332      0.431      0.325      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20      1.47G      1.376      1.471      1.156          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.254      0.384      0.328      0.195

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20      1.47G      1.353      1.414      1.207         14        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.4s
                   all         19        103       0.32      0.386      0.344      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20      1.47G      1.386      1.349      1.186          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.5s
                   all         19        103      0.308      0.434      0.347      0.216

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20      1.47G      1.334       1.29      1.156          6        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.3it/s 0.6s0.4s
                   all         19        103        0.3        0.4      0.342      0.215

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20      1.47G      1.321      1.266      1.144          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.3it/s 0.6s0.5s
                   all         19        103      0.304      0.408      0.324       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20      1.47G      1.347      1.245      1.138          4        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.1it/s 0.6s0.5s
                   all         19        103      0.319      0.417      0.327      0.211

20 epochs completed in 0.117 hours.
Optimizer stripped from C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_8\weights\last.pt, 22.5MB
Optimizer stripped from C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_8\weights\best.pt, 22.5MB

Validating C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_8\weights\best.pt...
Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
Model summary (fused): 73 layers, 11,129,067 parameters, 0 gradients, 28.5 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.8it/s 1.1s0.7s
                   all         19        103      0.307      0.433      0.348      0.217
Speed: 1.0ms preprocess, 35.9ms inference, 0.0ms loss, 3.7ms postprocess per image
Results saved to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_8
Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
Model summary (fused): 73 layers, 11,129,067 parameters, 0 gradients, 28.5 GFLOPs
val: Fast image access  (ping: 0.20.1 ms, read: 437.4277.6 MB/s, size: 407.4 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.4s/it 14.8s<42.7s
                   all         19        103      0.323      0.426      0.349      0.214
Speed: 33.9ms preprocess, 78.8ms inference, 0.0ms loss, 13.7ms postprocess per image
Results saved to C:\Users\Enzo\Desktop\rp\runs\detect\val-12

[I 2026-06-12 02:48:25,533] Trial 8 finished with value: 0.34867287656811174 and parameters: {'epochs': 20, 'batch_size': 4, 'learning_rate': 0.0007264257237865342, 'weight_decay': 0.0030161343547410197, 'optimizer': 'AdamW', 'img_size': 640, 'momentum': 0.8736991804426751, 'scheduler': 'cosine', 'patience': 10}. Best is trial 2 with value: 0.3987440397835331.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=110, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=2.0494637010912413e-05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.9664647506220805, mosaic=1.0, multi_scale=0.0, name=YOLO_trial_9, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adam, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_9, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005867672031797894, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.1 ms, read: 140.141.7 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 938.6358.7 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: Adam(lr=2.0494637010912413e-05, momentum=0.9664647506220805) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005867672031797894), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_9\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_trial_9
Starting training for 110 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/110      1.72G      2.353      8.636      1.656         11        640: 100% ━━━━━━━━━━━━ 46/46 2.4it/s 18.8s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.2it/s 0.7s0.6s
                   all         19        103   0.000781     0.0903    0.00122   0.000472

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/110      1.72G      2.248      5.192      1.471          3        640: 100% ━━━━━━━━━━━━ 46/46 2.6it/s 17.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103    0.00445      0.198    0.00494    0.00224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/110      1.72G       2.02      4.434      1.399          8        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103    0.00362      0.252    0.00853    0.00473

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/110      1.72G      2.117       4.44      1.441         13        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.4s
                   all         19        103    0.00358      0.253    0.00731    0.00408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/110      1.72G      1.997      4.381      1.437          7        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.8it/s 0.6s0.5s
                   all         19        103    0.00633      0.311     0.0135    0.00735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/110      1.72G       2.05      4.199      1.394          8        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.4it/s 0.6s0.5s
                   all         19        103    0.00746      0.318      0.022      0.012

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/110      1.72G      2.009      4.012      1.406         13        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.8it/s 0.6s0.5s
                   all         19        103    0.00738      0.325     0.0321     0.0205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/110      1.72G      1.878      4.144      1.401         12        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.126      0.133      0.047     0.0302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/110      1.72G      1.978      3.813      1.426         11        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.4it/s 0.7s0.5s
                   all         19        103      0.594     0.0726     0.0534     0.0351

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/110      1.72G      1.877       3.75      1.357          4        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.722     0.0557     0.0667     0.0436

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/110      1.72G      1.909      3.765      1.351         17        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.722     0.0625     0.0705     0.0459

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/110      1.72G      1.882      3.518      1.354         12        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.1it/s 0.6s0.5s
                   all         19        103      0.733     0.0763      0.088     0.0574

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/110      1.72G      1.856      3.808      1.354          2        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.1it/s 0.6s0.5s
                   all         19        103       0.74     0.0846     0.0989     0.0624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/110      1.72G      1.824      3.446      1.275         34        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.6it/s 0.7s0.5s
                   all         19        103      0.745     0.0935      0.108     0.0653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/110      1.72G      1.844       3.39      1.329          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.758      0.111       0.11     0.0653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/110      1.72G      1.927      3.505       1.33          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103      0.761      0.111      0.116     0.0669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/110      1.72G      1.724      3.184      1.279          8        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 16.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.778      0.118      0.126     0.0709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/110      1.72G      1.865      3.188      1.321         18        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.5it/s 0.7s0.5s
                   all         19        103      0.426      0.131      0.131     0.0744

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/110      1.72G      1.735      3.401      1.272          6        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.311      0.147      0.132     0.0742

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/110      1.72G      1.807      3.098       1.25          5        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.8it/s 0.6s0.5s
                   all         19        103      0.306      0.158      0.136     0.0795

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/110      1.72G      1.886      3.159      1.267         32        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.319      0.174      0.148     0.0866

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/110      1.72G      1.827      3.015      1.278          9        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.8it/s 0.6s0.5s
                   all         19        103      0.317      0.183       0.15     0.0876

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/110      1.72G      1.786      2.959      1.282          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.1it/s 0.6s0.5s
                   all         19        103      0.325      0.193      0.151     0.0882

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/110      1.72G      1.752      2.952      1.268         14        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.322      0.193      0.148     0.0842

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/110      1.72G      1.713      2.763      1.247          3        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.2it/s 0.6s0.5s
                   all         19        103      0.319      0.193      0.158     0.0927

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/110      1.72G       1.72      2.883      1.225          5        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.204      0.193      0.149     0.0853

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/110      1.72G      1.706      2.715      1.262         21        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103      0.199      0.193       0.15     0.0861

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/110      1.72G       1.68      2.946      1.268          9        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103      0.325      0.223      0.155     0.0878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/110      1.72G      1.709      2.902      1.248          6        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.3s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103      0.214       0.23      0.158     0.0887

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/110      1.72G      1.655      2.775      1.224          5        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.1it/s 0.6s0.5s
                   all         19        103      0.342      0.229      0.158     0.0878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/110      1.72G      1.719      2.822      1.234         14        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.9it/s 0.6s0.5s
                   all         19        103      0.193      0.243      0.168     0.0925

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/110      1.72G       1.62      2.703      1.227          5        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.186      0.226      0.178     0.0975

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/110      1.72G      1.675      2.614      1.239          6        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.1it/s 0.6s0.5s
                   all         19        103      0.195      0.228      0.176     0.0973

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/110      1.72G       1.62      2.464      1.186         30        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.256      0.205      0.177     0.0956

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/110      1.72G      1.658      2.501      1.226         10        640: 100% ━━━━━━━━━━━━ 46/46 2.7it/s 17.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.0it/s 0.6s0.5s
                   all         19        103      0.367      0.217      0.178     0.0978


[I 2026-06-12 03:24:38,138] Trial 9 finished with value: 0.2979538070852893 and parameters: {'epochs': 110, 'batch_size': 4, 'learning_rate': 2.0494637010912413e-05, 'weight_decay': 0.0005867672031797894, 'optimizer': 'Adam', 'img_size': 640, 'momentum': 0.9664647506220805, 'scheduler': 'step', 'patience': 20}. Best is trial 2 with value: 0.3987440397835331.

Melhor score em VAL para YOLO: 0.3987
Melhores hiperparametros em YOLO: {'epochs': 120, 'batch_size': 8, 'learning_rate': 0.0009885477189256258, 'weight_decay': 0.0001010433394006205, 'optimizer': 'AdamW', 'img_size': 512, 'momentum': 0.8765697627073381, 'scheduler': 'step', 'patience': 30}
Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=120, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0009885477189256258, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.8765697627073381, mosaic=1.0, multi_scale=0.0, name=YOLO_final, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_final, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0001010433394006205, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2119531  ultralytics.nn.modules.head.Detect           [9, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,139,083 parameters, 11,139,067 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.30.5 ms, read: 158.834.8 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 976.3317.5 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: AdamW(lr=0.0009885477189256258, momentum=0.8765697627073381) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0001010433394006205), 63 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_final\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\YOLO\YOLO_final
Starting training for 120 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/120      1.78G      2.438      9.601      1.624         23        512: 100% ━━━━━━━━━━━━ 23/23 1.9it/s 11.9s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.8s
                   all         19        103      0.499     0.0625     0.0561     0.0254

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/120      1.78G      2.051      3.638      1.295         14        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.293      0.163      0.138      0.085

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/120      1.78G      1.842      3.015      1.234         12        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s1.0s
                   all         19        103       0.54      0.107      0.097     0.0344

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/120      1.78G      1.937      2.882      1.226         14        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.318      0.267      0.222       0.12

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/120      1.78G      1.779      2.609      1.208         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103       0.17      0.188      0.187       0.11

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/120      1.78G      1.767        2.6      1.195         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.378      0.184      0.159     0.0946

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/120      1.78G       1.78      2.368      1.193         16        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.2s
                   all         19        103       0.24      0.262      0.178     0.0962

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/120      1.78G      1.609      2.207       1.12         53        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s1.1s
                   all         19        103       0.25      0.295      0.233      0.137

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/120      1.78G      1.628      2.035       1.11         72        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.191      0.286      0.206      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/120      1.78G      1.705      2.024       1.14         35        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103      0.353      0.385       0.24      0.151

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/120      1.78G      1.669       1.99      1.112         29        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.289      0.321      0.266      0.154

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/120      1.78G      1.567      1.961      1.138         15        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.415      0.417      0.246      0.141

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/120      1.78G      1.563      1.959      1.117         25        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s1.1s
                   all         19        103      0.198      0.307      0.213       0.13

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/120      1.78G       1.58       1.69      1.078         39        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s1.1s
                   all         19        103      0.398      0.313      0.286      0.176

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/120      1.78G      1.543       1.69      1.089         10        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.487      0.356      0.274      0.164

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/120      1.78G      1.559      1.629      1.053         44        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.0s
                   all         19        103       0.42      0.261      0.284      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/120      1.78G      1.544      1.636      1.093         10        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.289      0.394      0.309      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/120      1.78G      1.484       1.52      1.063         20        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.381      0.279      0.297      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/120      1.78G      1.583      1.593      1.063         45        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.329      0.366      0.312      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/120      1.78G      1.436      1.469      1.034         48        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s1.1s
                   all         19        103       0.41      0.389      0.307      0.191

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/120      1.78G      1.418      1.478      1.046         21        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.403      0.417      0.312      0.193

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/120      1.78G      1.431      1.356      1.053         24        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.5s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.358      0.391      0.342      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/120      1.78G      1.395      1.347      1.034         28        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s1.1s
                   all         19        103      0.506      0.358      0.351      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/120      1.78G      1.439      1.339      1.044         37        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s1.2s
                   all         19        103      0.437      0.418      0.348      0.204

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/120      1.78G      1.487      1.349      1.023         49        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.436      0.396      0.335      0.185

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/120      1.78G      1.397      1.338      1.038         18        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103       0.27      0.367      0.319      0.203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/120      1.78G       1.37       1.24      1.015         35        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.263      0.358      0.288      0.175

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/120      1.78G      1.454      1.374      1.057         58        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s1.2s
                   all         19        103      0.415      0.374      0.308      0.187

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/120      1.78G       1.36      1.261      1.062         31        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.329      0.415      0.333        0.2

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/120      1.78G      1.415       1.25      1.065         52        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.319      0.382      0.323      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/120      1.78G      1.429      1.249       1.06         21        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s1.1s
                   all         19        103        0.3      0.407      0.331      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/120      1.78G      1.324      1.217      1.025         33        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s1.1s
                   all         19        103      0.318      0.343      0.321      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/120      1.78G       1.29      1.195     0.9996         27        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.7s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s1.1s
                   all         19        103      0.294      0.424      0.329      0.198

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/120      1.78G      1.361      1.232      1.045         59        512: 100% ━━━━━━━━━━━━ 23/23 2.4it/s 9.6s0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s1.1s
                   all         19        103      0.418      0.461      0.324      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

[I 2026-06-12 03:41:11,780] A new study created in memory with name: no-name-86607fc7-090b-4887-acee-fbb4d96197d6

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/rtdetr-l.pt to 'rtdetr-l.pt': 100% ━━━━━━━━━━━━ 63.4MB 10.3MB/s 6.2s6.2s<0.0ss
Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.000679622153478893, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.8953767588737571, mosaic=1.0, multi_scale=0.0, name=T-DETR_trial_0, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_0, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9
WARNING no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7320347  ultralytics.nn.modules.head.RTDETRDecoder    [9, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,824,571 parameters, 32,824,571 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.20.2 ms, read: 467.5202.2 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 845.5265.6 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19 19.0Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.000679622153478893' and 'momentum=0.8953767588737571' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000769, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_0\labels.jpg...
Image sizes 512 train, 512 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_0
Starting training for 20 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
WARNING CUDA out of memory with batch=8. Reducing to batch=4 and retrying (1/3).
train: Fast image access  (ping: 0.50.1 ms, read: 140.835.8 MB/s, size: 473.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.30.3 ms, read: 463.4321.2 MB/s, size: 838.4 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.000679622153478893' and 'momentum=0.8953767588737571' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000769, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
: 0% ──────────── 0/23  38.3s

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
WARNING CUDA out of memory with batch=4. Reducing to batch=2 and retrying (2/3).
train: Fast image access  (ping: 0.20.1 ms, read: 139.565.5 MB/s, size: 441.3 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.40.4 ms, read: 121.633.1 MB/s, size: 414.7 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.000679622153478893' and 'momentum=0.8953767588737571' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000769, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
: 0% ──────────── 0/46  36.3s

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/20      3.82G       2.41      8.277     0.8591         10       1024: 100% ━━━━━━━━━━━━ 92/92 6.0s/it 9:153.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.4it/s 1.4s4.0s
                   all         19        103    0.00306    0.00694    0.00241   0.000481

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/20      4.06G      2.621      1.867       1.18          2       1024: 100% ━━━━━━━━━━━━ 92/92 2.9s/it 4:262.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.5it/s 1.3s3.7s
                   all         19        103    0.00156     0.0833   0.000672    0.00037

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/20      4.12G      2.103     0.6947     0.5839          5       1024: 100% ━━━━━━━━━━━━ 92/92 5.6s/it 8:392.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.5it/s 1.4s3.8s
                   all         19        103   0.000188     0.0625   0.000318   0.000117

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/20      4.16G       1.68      0.657     0.3222          3       1024: 100% ━━━━━━━━━━━━ 92/92 2.7s/it 4:112.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.6it/s 1.2s3.4s
                   all         19        103   0.000596      0.103     0.0044    0.00165

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/20      4.16G      1.842     0.6047     0.4383          2       1024: 100% ━━━━━━━━━━━━ 92/92 3.9s/it 6:013.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.4it/s 1.4s4.0s
                   all         19        103     0.0113     0.0865    0.00546    0.00259

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/20      4.01G      1.429     0.9414     0.3063          4       1024: 100% ━━━━━━━━━━━━ 92/92 2.0s/it 3:031.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.5it/s 1.3s3.6s
                   all         19        103    0.00156      0.181     0.0127    0.00684

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/20      4.01G      1.712     0.9371     0.3593          7       1024: 100% ━━━━━━━━━━━━ 92/92 3.3s/it 5:052.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.4it/s 1.4s3.9s
                   all         19        103    0.00224      0.176     0.0284     0.0127

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/20      4.06G      1.528     0.9877     0.3183         11       1024: 100% ━━━━━━━━━━━━ 92/92 3.0s/it 4:362.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.6it/s 1.3s3.5s
                   all         19        103    0.00927       0.23     0.0355     0.0186

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/20      3.99G      1.127      1.137     0.1903          7       1024: 100% ━━━━━━━━━━━━ 92/92 2.2s/it 3:201.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.5it/s 1.4s3.8s
                   all         19        103      0.364       0.17     0.0482     0.0331

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/20      3.98G     0.9881      1.208     0.1537          5       1024: 100% ━━━━━━━━━━━━ 92/92 2.2s/it 3:272.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.6it/s 1.2s3.4s
                   all         19        103      0.349      0.126     0.0263     0.0157
Closing dataloader mosaic

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/20       1.8G     0.7371      1.426      0.176         15        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 57.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.1s
                   all         19        103      0.136       0.23       0.04     0.0247

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      12/20      1.81G     0.5534       1.55    0.08879          2        512: 0% ──────────── 0/92  0.9s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/20      1.81G     0.6625      1.512     0.1704          1        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 56.9s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103      0.411      0.125     0.0679     0.0502

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/20      1.82G     0.3265          2    0.05305          3        512: 0% ──────────── 0/92  1.1s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/20      1.82G     0.6057      1.369     0.1375          1        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.0s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103      0.644      0.194      0.126     0.0804

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/20      1.81G     0.3003       1.29    0.07546          2        512: 0% ──────────── 0/92  1.2s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/20      1.81G     0.5496      1.217     0.1344          1        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.0s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103      0.342      0.225      0.166      0.109

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/20      1.83G      0.665     0.6814    0.07677          4        512: 0% ──────────── 0/92  1.1s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/20      1.83G     0.5021      1.142     0.1129          1        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103      0.461      0.223      0.139     0.0887

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/20      1.83G     0.5561      1.152    0.05833          3        512: 0% ──────────── 0/92  1.2s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/20      1.83G     0.5053      1.116     0.1133          8        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.0s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103      0.485      0.249      0.169      0.112

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/20      1.81G     0.1061      1.332    0.03843          1        512: 0% ──────────── 0/92  1.2s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/20      1.81G     0.4927      1.065     0.1002          1        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103      0.609       0.22      0.164      0.106

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/20      1.83G     0.2249       1.22    0.03395          2        512: 0% ──────────── 0/92  1.0s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/20      1.83G     0.4693       1.05     0.1029          1        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.0s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103      0.588      0.194      0.201      0.128

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/20      1.73G     0.3099     0.7534    0.06136          4        512: 0% ──────────── 0/92  1.3s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/20      1.78G     0.4641     0.9829     0.0993          1        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.0s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103       0.13      0.383      0.212      0.138

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/20      1.81G     0.3865     0.9982    0.09161          3        512: 0% ──────────── 0/92  1.1s

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/20      1.81G     0.4544     0.9492    0.09611          2        512: 100% ━━━━━━━━━━━━ 92/92 1.6it/s 59.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.7it/s 1.2s3.2s
                   all         19        103       0.27      0.295      0.207      0.134

20 epochs completed in 1.097 hours.
Optimizer stripped from C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_0\weights\last.pt, 66.2MB
Optimizer stripped from C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_0\weights\best.pt, 66.2MB

Validating C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_0\weights\best.pt...
Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
rt-detr-l summary: 310 layers, 32,002,235 parameters, 0 gradients, 103.5 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.4it/s 1.5s3.0s
                   all         19        103      0.137      0.389      0.214      0.139
Speed: 0.4ms preprocess, 51.7ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_0
Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
rt-detr-l summary: 310 layers, 32,002,235 parameters, 0 gradients, 103.5 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 1067.9133.7 MB/s, size: 212.5 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 7.5s/it 15.0s<47.7s
                   all         19        103      0.131      0.384      0.212      0.138
Speed: 9.1ms preprocess, 65.1ms inference, 0.1ms loss, 3.2ms postprocess per image
Results saved to C:\Users\Enzo\Desktop\rp\runs\detect\val-15

[I 2026-06-12 04:48:20,254] Trial 0 finished with value: 0.2121015211661377 and parameters: {'epochs': 20, 'batch_size': 8, 'learning_rate': 0.000679622153478893, 'weight_decay': 0.0028680579691988395, 'optimizer': 'SGD', 'img_size': 512, 'momentum': 0.8953767588737571, 'scheduler': 'onecycle', 'patience': 10}. Best is trial 0 with value: 0.2121015211661377.

Ultralytics 8.4.66  Python-3.11.0 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=C:\Users\Enzo\Desktop\rp\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=120, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.00035933925290393734, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.9051560353928501, mosaic=1.0, multi_scale=0.0, name=T-DETR_trial_1, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=25, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_1, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=9
WARNING no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7320347  ultralytics.nn.modules.head.RTDETRDecoder    [9, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,824,571 parameters, 32,824,571 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.20.1 ms, read: 130.239.3 MB/s, size: 233.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.10.1 ms, read: 895.2328.8 MB/s, size: 422.8 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.00035933925290393734' and 'momentum=0.9051560353928501' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000769, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_1\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to C:\Users\Enzo\Desktop\rp\training_artifacts\T-DETR\T-DETR_trial_1
Starting training for 120 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
WARNING CUDA out of memory with batch=4. Reducing to batch=2 and retrying (1/3).
train: Fast image access  (ping: 0.10.1 ms, read: 136.862.6 MB/s, size: 473.7 KB)
train: Scanning C:\Users\Enzo\Desktop\rp\datasets\train\labels.cache... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183  0.0s
val: Fast image access  (ping: 0.40.3 ms, read: 141.071.4 MB/s, size: 838.4 KB)
val: Scanning C:\Users\Enzo\Desktop\rp\datasets\val\labels.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.00035933925290393734' and 'momentum=0.9051560353928501' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000769, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
: 0% ──────────── 0/46  37.2s

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      1/120      5.59G      2.308      8.446      0.835         10       1280: 100% ━━━━━━━━━━━━ 92/92 23.1s/it 35:2318.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.4it/s 2.2s1.7s
                   all         19        103   0.000637     0.0208   0.000135   2.77e-05

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      2/120      6.02G      2.525       2.03       1.06          2       1280: 100% ━━━━━━━━━━━━ 92/92 19.0s/it 29:0518.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2s/it 3.7s2.0ss
                   all         19        103   0.000336     0.0556   0.000226   5.68e-05

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      3/120      5.92G      1.983     0.7365     0.4852          5       1280: 100% ━━━━━━━━━━━━ 92/92 24.2s/it 37:0218.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.7s1.9ss
                   all         19        103    0.00101     0.0625   0.000194   5.91e-05

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      4/120      5.92G      1.681       0.69     0.3086          3       1280: 100% ━━━━━━━━━━━━ 92/92 24.8s/it 38:0515.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.8s1.9ss
                   all         19        103   0.000438     0.0812   0.000534    0.00019

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      5/120      5.92G      1.466     0.8159       0.31          2       1280: 100% ━━━━━━━━━━━━ 92/92 24.0s/it 36:4815.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.5it/s 2.1s1.6s
                   all         19        103    0.00147     0.0903    0.00935     0.0041

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      6/120      5.91G       1.59     0.8849     0.3013          4       1280: 100% ━━━━━━━━━━━━ 92/92 18.4s/it 28:1214.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.7s1.9ss
                   all         19        103      0.225     0.0833     0.0316     0.0166

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      7/120      5.93G      1.314      1.126     0.2391          7       1280: 100% ━━━━━━━━━━━━ 92/92 19.9s/it 30:3215.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.6s1.8ss
                   all         19        103      0.123      0.193     0.0435     0.0204

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      8/120      5.93G      1.084      1.185     0.1741         11       1280: 100% ━━━━━━━━━━━━ 92/92 23.5s/it 36:0617.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.0it/s 2.9s1.9ss
                   all         19        103      0.137      0.142     0.0653     0.0338

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      9/120         6G     0.7176      1.418     0.1016          7       1280: 100% ━━━━━━━━━━━━ 92/92 21.1s/it 32:2416.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.0it/s 2.9s1.9ss
                   all         19        103      0.482      0.246     0.0606     0.0347

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     10/120       5.9G     0.7148      1.345    0.09134          5       1280: 100% ━━━━━━━━━━━━ 92/92 22.8s/it 34:5817.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.5it/s 2.0s1.6s
                   all         19        103      0.476      0.175     0.0442     0.0276

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     11/120      5.92G     0.7199      1.302     0.1018          5       1280: 100% ━━━━━━━━━━━━ 92/92 19.8s/it 30:1915.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.0s/it 3.0s1.9ss
                   all         19        103      0.482     0.0525     0.0635     0.0386

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     12/120      6.02G     0.7178      1.249      0.103          5       1280: 100% ━━━━━━━━━━━━ 92/92 20.3s/it 31:0715.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.8s1.9ss
                   all         19        103      0.588     0.0935     0.0918     0.0436

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     13/120      6.02G     0.6026      1.171    0.07393          7       1280: 100% ━━━━━━━━━━━━ 92/92 21.7s/it 33:2118.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.6s1.8ss
                   all         19        103      0.606      0.181      0.157     0.0804

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     14/120      5.92G     0.5458        1.1    0.05958          1       1280: 100% ━━━━━━━━━━━━ 92/92 20.7s/it 31:4816.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.7s1.9ss
                   all         19        103      0.689      0.208      0.137     0.0705

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     15/120         6G     0.5578      1.018    0.06055         19       1280: 100% ━━━━━━━━━━━━ 92/92 20.4s/it 31:1313.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3it/s 2.2s1.7s
                   all         19        103      0.112      0.283      0.175        0.1

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

c:\Users\Enzo\Desktop\rp\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     16/120      5.93G     0.5355     0.9727     0.0554         46       1280: 60% ━━━━━━━───── 56/92 30.1s/it 26:37<18:04

## Célula 5 - Avaliação Final

Aqui são calculadas as métricas finais no conjunto de teste e, se possível, geradas predições qualitativas.

In [ ]:
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def load_best_artifact(summary_path: Path) -> tuple[str, Path, dict[str, Any]]:
    if not summary_path.exists():
        raise FileNotFoundError(f'Training summary nao encontrado: {summary_path.resolve()}')
    table = pd.read_csv(summary_path)
    if table.empty:
        raise ValueError('training_summary.csv esta vazio.')
    best_row = table.sort_values('Melhor_Metrica_VAL', ascending=False).iloc[0]
    return str(best_row['Modelo']), Path(str(best_row['Peso'])), json.loads(str(best_row['Hiperparametros']))


def metrics_to_row(model_name: str, metrics: dict[str, float]) -> dict[str, float | str]:
    return {
        'Modelo': model_name,
        'Accuracy': metrics.get('Accuracy', 0.0),
        'Precision': metrics.get('Precision', 0.0),
        'Recall': metrics.get('Recall', 0.0),
        'F1-Score': metrics.get('F1-Score', 0.0),
        'mAP50': metrics.get('mAP50', 0.0),
        'mAP50-95': metrics.get('mAP50-95', 0.0),
    }


def evaluate_model_on_test(model_name: str, backend: Any, weights: Path, class_names: list[str]) -> tuple[dict[str, float | str], pd.DataFrame, np.ndarray, dict[str, float]]:
    ground_truth = collect_ground_truth(TEST_ROOT)
    predictions = backend.predict(weights, TEST_ROOT / 'images', PROJECT_ROOT / 'test_predictions' / model_name.replace(' ', '_').lower())
    ap_table, confusion_matrix, metrics = evaluate_detections(ground_truth, predictions, class_names)
    save_confusion_outputs(confusion_matrix, class_names, model_name)
    ap_table = ap_table.copy()
    ap_table.insert(0, 'Modelo', model_name)
    return metrics_to_row(model_name, metrics), ap_table, confusion_matrix, metrics


best_model_name, best_weights, best_params = load_best_artifact(TRAINING_SUMMARY_CSV)
print(f'Melhor modelo encontrado por validacao: {best_model_name}')
print(f'Melhores hiperparametros: {best_params}')
print(f'Caminho do peso salvo: {best_weights.resolve()}')

metric_rows: list[dict[str, float | str]] = []
per_class_tables: list[pd.DataFrame] = []
evaluation_details: dict[str, dict[str, Any]] = {}

for candidate_model in COMPARE_MODELS:
    artifact = ARTIFACTS_BY_MODEL[candidate_model]
    backend = build_backend(candidate_model, CLASS_NAMES, DATASET_YAML, ARTIFACTS_DIR / candidate_model)
    metric_row, ap_table, confusion_matrix, metrics = evaluate_model_on_test(candidate_model, backend, artifact.best_weights, CLASS_NAMES)
    metric_rows.append(metric_row)
    per_class_tables.append(ap_table)
    evaluation_details[candidate_model] = {
        'metrics': metrics,
        'per_class_ap': ap_table,
        'confusion_matrix': confusion_matrix,
    }

final_metrics_table = pd.DataFrame(metric_rows).sort_values('mAP50', ascending=False).reset_index(drop=True)
per_class_metrics_table = pd.concat(per_class_tables, ignore_index=True)

FINAL_METRICS_CSV = PROJECT_ROOT / 'final_test_metrics_by_model.csv'
FINAL_PER_CLASS_CSV = PROJECT_ROOT / 'final_test_per_class_metrics.csv'
final_metrics_table.to_csv(FINAL_METRICS_CSV, index=False, encoding='utf-8')
per_class_metrics_table.to_csv(FINAL_PER_CLASS_CSV, index=False, encoding='utf-8')

display(final_metrics_table)
display(per_class_metrics_table)

print('Resumo final')
print(f'Melhor modelo por VAL: {best_model_name}')
print(f'Melhores hiperparametros por VAL: {best_params}')
print(f'Peso salvo: {best_weights.resolve()}')
print(f'Metricas finais por modelo: {FINAL_METRICS_CSV.resolve()}')
print(f'Metricas finais por classe: {FINAL_PER_CLASS_CSV.resolve()}')
print(f'Matrizes de confusao: {CONFUSION_MATRIX_DIR.resolve()}')
print('TEST foi usado exclusivamente na avaliacao final.')
print('TEST nao participa do treinamento, da busca Optuna nem da selecao de hiperparametros.')